# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ARRIVED', 'Arrived'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('ONLEAVE', 'On leave'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('ENTERED_IN_ERROR', 'Entered in error')], default='IN_PROGRESS', max_length=50)),
                ('encounter_class', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='organizations.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='practitioners.practitioner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_encounters', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('SUPERSEDED', 'Superseded'), ('ENTERED_IN_ERROR', 'Entered in error')], default='CURRENT', max_length=50)),
                ('doc_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('object_url', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_documents', to='practitioners.practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='tenancy.tenant')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.clinicalencounter')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RECURRENCE', 'Recurrence'), ('RELAPSE', 'Relapse'), ('INACTIVE', 'Inactive'), ('REMISSION', 'Remission'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('PROVISIONAL', 'Provisional'), ('DIFFERENTIAL', 'Differential'), ('CONFIRMED', 'Confirmed'), ('REFUTED', 'Refuted'), ('ENTERED_IN_ERROR', 'Entered in error')], default='UNCONFIRMED', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(blank=True, max_length=255)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('onset_date', models.DateTimeField(blank=True, null=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_conditions', to='tenancy.tenant')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.clinicalencounter')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final'), ('AMENDED', 'Amended'), ('CORRECTED', 'Corrected'), ('CANCELLED', 'Cancelled'), ('ENTERED_IN_ERROR', 'Entered in error'), ('UNKNOWN', 'Unknown')], default='FINAL', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(blank=True, max_length=255)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('value_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=50)),
                ('value_string', models.CharField(blank=True, max_length=255)),
                ('interpretation', models.CharField(blank=True, max_length=50)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_observations', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalDiagnosticReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PARTIAL', 'Partial'), ('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final'), ('AMENDED', 'Amended'), ('CORRECTED', 'Corrected'), ('APPENDED', 'Appended'), ('CANCELLED', 'Cancelled'), ('ENTERED_IN_ERROR', 'Entered in error'), ('UNKNOWN', 'Unknown')], default='FINAL', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(blank=True, max_length=255)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_reports', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to='tenancy.tenant')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.clinicalencounter')),
                ('observations', models.ManyToManyField(blank=True, related_name='diagnostic_reports', to='clinical.clinicalobservation')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('NOT_DONE', 'Not done'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('ENTERED_IN_ERROR', 'Entered in error'), ('STOPPED', 'Stopped'), ('UNKNOWN', 'Unknown')], default='COMPLETED', max_length=50)),
                ('medication_name', models.CharField(max_length=255)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('dosage_text', models.TextField(blank=True)),
                ('reason_not_done', models.CharField(blank=True, max_length=255)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_administrations', to='patients.patient')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practitioners.practitioner')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
    ]
