# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('prescription', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministrationrecord',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='medicationadministrationrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='clinicalencounter',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_clinical_enc_patient'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_clinical_document'),
        ),
        migrations.AddIndex(
            model_name='clinicalcondition',
            index=models.Index(fields=['tenant', 'patient', 'clinical_status'], name='ix_clinical_condition'),
        ),
        migrations.AddIndex(
            model_name='clinicalobservation',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_clinical_observation'),
        ),
        migrations.AddIndex(
            model_name='clinicaldiagnosticreport',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_clinical_report'),
        ),
        migrations.AddIndex(
            model_name='medicationadministrationrecord',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_clinical_med_admin'),
        ),
    ]
