# Generated by Django 5.1.15 on 2026-07-28 11:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_qualitydecision_receivingsession_receivingscan_and_more'),
        ('tenancy', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_above_lowest', models.CharField(choices=[('REQUIRE_REASON', 'Require a stated reason'), ('BLOCK', 'Award the lowest quotation only'), ('ALLOW', 'Allow without explanation')], default='REQUIRE_REASON', max_length=20)),
                ('award_variance_tolerance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_policy', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'procurement policies',
            },
        ),
    ]
