# Generated by Django 5.1.15 on 2026-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_batch_quality_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedbatch',
            name='quality_status',
            field=models.CharField(choices=[('PENDING_INSPECTION', 'Pending Inspection'), ('QUARANTINED', 'Quarantined'), ('PARTIALLY_RELEASED', 'Partially Released'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected'), ('RETURN_PENDING', 'Return Pending'), ('RETURNED', 'Returned'), ('DESTROYED', 'Destroyed')], db_index=True, default='PENDING_INSPECTION', max_length=32),
        ),
    ]
