# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_global', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=120)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=120)),
                ('strength', models.CharField(blank=True, max_length=120)),
                ('gtin', models.CharField(blank=True, max_length=32)),
                ('primary_barcode', models.CharField(blank=True, max_length=80)),
                ('atc_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(max_length=160)),
                ('source_version', models.CharField(max_length=80)),
                ('licence_identifier', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='medicines.medicine')),
            ],
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', True), ('tenant__isnull', True)), models.Q(('is_global', False), ('tenant__isnull', False)), _connector='OR'), name='ck_medicine_explicit_scope'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code'), name='uq_medicine_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True), ('tenant__isnull', True)), fields=('code',), name='uq_medicine_global_code'),
        ),
        migrations.AddConstraint(
            model_name='medicineidentifier',
            constraint=models.UniqueConstraint(fields=('system', 'value'), name='uq_medicine_identifier'),
        ),
    ]
