# Generated by Django 5.1.15 on 2026-07-26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicines", "0002_administrationroute_doseform_activesubstance_and_more"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCatalogueProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_code", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SELECTED", "Selected"),
                            ("REMOVED", "Removed"),
                        ],
                        default="SELECTED",
                        max_length=20,
                    ),
                ),
                ("selected_at", models.DateTimeField()),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "master_medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_catalogue_products",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removed_catalogue_products",
                        to="identity.user",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_catalogue_products",
                        to="identity.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogue_products",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tenantcatalogueproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "master_medicine"),
                name="uq_tenant_catalogue_master_medicine",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantcatalogueproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "tenant_code"),
                name="uq_tenant_catalogue_code",
            ),
        ),
    ]
