# Generated by Django 5.1.15 on 2026-07-22 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=16)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
