# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fhir', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fhiridempotencyrecord',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhir_idempotency_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fhiridempotencyrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_idempotency_records', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='fhiridempotencyrecord',
            index=models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='ix_fhir_idempotency_resource'),
        ),
        migrations.AddIndex(
            model_name='fhiridempotencyrecord',
            index=models.Index(fields=['tenant', 'created_at'], name='ix_fhir_idempotency_created'),
        ),
        migrations.AddConstraint(
            model_name='fhiridempotencyrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uq_fhir_idempotency_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='fhiridempotencyrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resource_id__isnull', True), ('state', 'PROCESSING')), models.Q(('resource_id__isnull', False), ('state', 'COMPLETED')), _connector='OR'), name='ck_fhir_idempotency_state_resource'),
        ),
    ]
