# Generated by Django 5.1.15 on 2026-07-23 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryledgerentry',
            name='uq_inventory_ledger_idempotency',
        ),
        migrations.AddConstraint(
            model_name='inventoryledgerentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_ledger_idempotency'),
        ),
    ]
