# Generated by Django 5.1.15 on 2026-07-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryledgerentry_uq_inventory_ledger_idempotency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryledgerentry',
            options={'ordering': ['-transaction_timestamp']},
        ),
    ]
