# Generated by Django 5.1.15 on 2026-07-26 04:45

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryledgerentry_options'),
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('INSPECT', 'Inspect'), ('PUTAWAY', 'Putaway'), ('PICK', 'Pick'), ('PACK', 'Pack'), ('DISPATCH', 'Dispatch'), ('TRANSFER_RECEIVE', 'Transfer Receive'), ('REPLENISH', 'Replenish'), ('COUNT', 'Count')], default='PICK', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventorybatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventorylocation')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BarcodeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=128)),
                ('barcode_type', models.CharField(default='GS1_128', max_length=64)),
                ('pack_conversion', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'barcode'), name='uq_barcode_master')],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
    ]
