# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('WARNING', 'Warning'), ('BLOCK', 'Block'), ('KNOWLEDGE_UNAVAILABLE', 'Knowledge unavailable'), ('ERROR', 'Error')], max_length=30)),
                ('context_hash', models.CharField(max_length=64)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=120)),
                ('rule_version', models.CharField(max_length=80)),
                ('rule_type', models.CharField(max_length=40)),
                ('source', models.CharField(max_length=200)),
                ('source_version', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('severity', models.CharField(max_length=20)),
                ('evidence_summary', models.TextField()),
                ('explanation', models.TextField()),
                ('recommended_action', models.TextField()),
                ('override_policy', models.CharField(max_length=20)),
                ('interacting_factor', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClinicalKnowledgeRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=80)),
                ('source', models.CharField(max_length=200)),
                ('source_version', models.CharField(max_length=100)),
                ('licence', models.CharField(max_length=200)),
                ('effective_date', models.DateField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('content_classification', models.CharField(default='DEMONSTRATION', max_length=50)),
                ('checksum_sha256', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalKnowledgeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.CharField(max_length=120)),
                ('rule_version', models.CharField(max_length=80)),
                ('rule_type', models.CharField(choices=[('DRUG_DRUG', 'Drug-drug interaction'), ('ALLERGY', 'Allergy'), ('DUPLICATE_THERAPY', 'Duplicate therapy'), ('CONDITION', 'Condition contraindication'), ('AGE', 'Age'), ('PREGNANCY', 'Pregnancy'), ('RENAL', 'Renal'), ('HEPATIC', 'Hepatic'), ('DOSE', 'Dose'), ('DURATION', 'Duration')], max_length=40)),
                ('primary_code', models.CharField(max_length=120)),
                ('interacting_code', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('BLOCK', 'Block')], max_length=20)),
                ('evidence_summary', models.TextField()),
                ('explanation', models.TextField()),
                ('recommended_action', models.TextField()),
                ('override_policy', models.CharField(choices=[('NONE', 'No override required'), ('REASON', 'Reason required'), ('PHARMACIST', 'Pharmacist capability and reason required'), ('PROHIBITED', 'Cannot override')], default='PHARMACIST', max_length=20)),
                ('criteria', models.JSONField(default=dict)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicineIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('strength_unit', models.CharField(blank=True, max_length=50)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('code_system', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_ingredients', to='tenancy.tenant')),
            ],
        ),
    ]
