# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cds', '0001_initial'),
        ('medicines', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescription', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalevaluation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_evaluations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicalevaluation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_evaluations', to='prescription.prescription'),
        ),
        migrations.AddField(
            model_name='clinicalevaluation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_evaluations', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='affected_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cds_findings', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cds.clinicalevaluation'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_findings', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalknowledgerelease',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_releases', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='clinicalevaluation',
            name='knowledge_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='cds.clinicalknowledgerelease'),
        ),
        migrations.AddField(
            model_name='clinicalknowledgerule',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='cds.clinicalknowledgerelease'),
        ),
        migrations.AddField(
            model_name='clinicalknowledgerule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='finding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='override', to='cds.clinicalfinding'),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescription'),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_overrides', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='medicineingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_links', to='cds.activeingredient'),
        ),
        migrations.AddField(
            model_name='medicineingredient',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_links', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='medicineingredient',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='activeingredient',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_cds_ingredient_tenant'),
        ),
        migrations.AddIndex(
            model_name='clinicalknowledgerelease',
            index=models.Index(fields=['tenant', 'is_active', 'effective_date'], name='ix_cds_release_active'),
        ),
        migrations.AddConstraint(
            model_name='clinicalknowledgerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code', 'version'), name='uq_cds_release_tenant'),
        ),
        migrations.AddConstraint(
            model_name='clinicalknowledgerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True), ('tenant__isnull', True)), fields=('code', 'version'), name='uq_cds_release_global'),
        ),
        migrations.AddConstraint(
            model_name='clinicalknowledgerelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', False), ('tenant__isnull', False)), models.Q(('is_global', True), ('tenant__isnull', True)), _connector='OR'), name='ck_cds_release_scope'),
        ),
        migrations.AddIndex(
            model_name='clinicalevaluation',
            index=models.Index(fields=['tenant', 'prescription', 'created_at'], name='ix_cds_eval_prescription'),
        ),
        migrations.AddIndex(
            model_name='clinicalknowledgerule',
            index=models.Index(fields=['tenant', 'rule_type', 'primary_code', 'is_active'], name='ix_cds_rule_lookup'),
        ),
        migrations.AddIndex(
            model_name='clinicalknowledgerule',
            index=models.Index(fields=['release', 'rule_type', 'interacting_code'], name='ix_cds_rule_factor'),
        ),
        migrations.AddConstraint(
            model_name='clinicalknowledgerule',
            constraint=models.UniqueConstraint(fields=('release', 'rule_id', 'rule_version'), name='uq_cds_rule_release'),
        ),
        migrations.AddConstraint(
            model_name='medicineingredient',
            constraint=models.UniqueConstraint(fields=('tenant', 'medicine', 'ingredient'), name='uq_cds_medicine_ingredient'),
        ),
    ]
