# Generated by Django 5.1.15 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalknowledgerule',
            name='criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
