# Generated by Django 5.1.15 on 2026-07-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_alter_clinicalknowledgerule_criteria'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clinicalknowledgerule',
            managers=[
            ],
        ),
    ]
