# Generated by Django 5.1.15 on 2026-07-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0004_alter_clinicalknowledgerule_managers'),
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('patients', '0001_initial'),
        ('prescription', '0002_prescription_ix_prescription_tenant_status_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalfinding',
            name='clinical_category',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_findings', to='prescription.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='resolution_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='resolution_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('OVERRIDDEN', 'Overridden'), ('INTERVENTION_REQUIRED', 'Intervention required'), ('RESOLVED', 'Resolved'), ('NOT_APPLICABLE', 'Not applicable')], default='OPEN', max_length=30),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalfinding',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='clinical_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='rule_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='clinicaloverride',
            name='supporting_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clinicalknowledgerule',
            name='rule_type',
            field=models.CharField(choices=[('DRUG_DRUG', 'Drug-drug interaction'), ('DRUG_DRUG_INTERACTION', 'Drug-drug interaction'), ('ALLERGY', 'Allergy'), ('DUPLICATE_THERAPY', 'Duplicate therapy'), ('CONDITION', 'Condition contraindication'), ('CONTRAINDICATION', 'Contraindication'), ('AGE', 'Age'), ('AGE_RESTRICTION', 'Age restriction'), ('PREGNANCY', 'Pregnancy'), ('PREGNANCY_WARNING', 'Pregnancy warning'), ('LACTATION_WARNING', 'Lactation warning'), ('RENAL', 'Renal'), ('RENAL_IMPAIRMENT', 'Renal impairment'), ('HEPATIC', 'Hepatic'), ('HEPATIC_IMPAIRMENT', 'Hepatic impairment'), ('DOSE', 'Dose'), ('DOSE_TOO_HIGH', 'Dose too high'), ('DOSE_TOO_LOW', 'Dose too low'), ('WEIGHT_BASED_DOSE', 'Weight-based dose'), ('MAXIMUM_DAILY_DOSE', 'Maximum daily dose'), ('FREQUENCY_TOO_HIGH', 'Frequency too high'), ('FREQUENCY_TOO_LOW', 'Frequency too low'), ('DURATION', 'Duration'), ('DURATION_TOO_LONG', 'Duration too long'), ('DURATION_TOO_SHORT', 'Duration too short'), ('CONTROLLED_MEDICINE_RULE', 'Controlled medicine rule'), ('EARLY_REPEAT', 'Early repeat'), ('LATE_REPEAT', 'Late repeat'), ('THERAPEUTIC_DUPLICATION', 'Therapeutic duplication'), ('FORMULARY_RESTRICTION', 'Formulary restriction'), ('INSUFFICIENT_DATA', 'Insufficient data')], max_length=40),
        ),
        migrations.AlterField(
            model_name='clinicalknowledgerule',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('INFORMATION', 'Information'), ('LOW', 'Low'), ('WARNING', 'Warning'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('BLOCK', 'Block'), ('CRITICAL', 'Critical')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='clinicalfinding',
            index=models.Index(fields=['tenant', 'prescription', 'resolution_status', 'severity'], name='ix_cds_finding_resolution'),
        ),
        migrations.AddConstraint(
            model_name='clinicalfinding',
            constraint=models.UniqueConstraint(fields=('evaluation', 'rule_id', 'rule_version', 'prescription_item', 'interacting_factor'), name='uq_clinical_finding_issue'),
        ),
    ]
