# Generated by Django 5.1.15 on 2026-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_clinicalfinding_clinical_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalfinding',
            name='interacting_factor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
