# Generated by Django 5.1.15 on 2026-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0007_pos_clinical_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='posclinicalscreening',
            name='screening_mode',
            field=models.CharField(default='STRICT', max_length=64),
        ),
        migrations.AlterField(
            model_name='posofflineclinicalpackage',
            name='rule_set_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
