"""Introduce OBJECT_SIGNING_KEY_V1 signing and revoke every legacy package.

Packages issued before this migration were signed with an HMAC keyed on
tenant.pk. A tenant UUID is public metadata, so those signatures establish no
provenance at all -- anyone holding the ID could have produced them.

They are therefore revoked rather than re-signed. Re-signing would assert that
we vouch for content we cannot vouch for. The records are kept intact for audit
and incident investigation; only their trust status changes.

Reversing this migration restores the previous schema. It does NOT restore trust:
signatures produced under the old scheme remain cryptographically worthless.
"""
# Generated by Django 5.1.15 on 2026-07-25 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone




def revoke_legacy_packages(apps, schema_editor):
    """Mark every pre-existing package as legacy and revoke it."""
    Package = apps.get_model("cds", "PosOfflineClinicalPackage")
    now = timezone.now()
    Package.objects.all().update(
        signing_version="LEGACY_TENANT_UUID_HMAC",
        is_active=False,
        revoked_at=now,
        revocation_reason="LEGACY_FORGEABLE_SIGNATURE",
    )


def unrevoke_is_not_supported(apps, schema_editor):
    """Reverse leg: deliberately does not restore trust.

    The schema is reversible; the trust decision is not. Old signatures stay
    untrustworthy no matter which direction the schema moves, so this leaves the
    revocation flags as data and lets the schema operations roll back around it.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0008_posclinicalscreening_screening_mode_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location'),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='context_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='revocation_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posofflineclinicalpackage',
            name='signing_version',
            field=models.CharField(choices=[('LEGACY_TENANT_UUID_HMAC', 'Legacy (forgeable)'), ('OBJECT_SIGNING_KEY_V1', 'Object signing key v1')], default='OBJECT_SIGNING_KEY_V1', max_length=40),
        ),
        migrations.RunPython(revoke_legacy_packages, unrevoke_is_not_supported),
    ]
