# Generated by Django 5.1.15 on 2026-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0009_offline_package_signing_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posclinicalauditevent',
            name='event_type',
            field=models.CharField(choices=[('SCREENING_REQUESTED', 'Screening requested'), ('SCREENING_COMPLETED', 'Screening completed'), ('FINDING_DISPLAYED', 'Finding displayed'), ('FINDING_ACKNOWLEDGED', 'Finding acknowledged'), ('PHARMACIST_REVIEW_REQUESTED', 'Pharmacist review requested'), ('PHARMACIST_AUTHENTICATED', 'Pharmacist authenticated'), ('FINDING_RESOLVED', 'Finding resolved'), ('OVERRIDE_RECORDED', 'Override recorded'), ('SCREENING_INVALIDATED', 'Screening invalidated'), ('OFFLINE_SCREENING_USED', 'Offline screening used'), ('SCREENING_UNAVAILABLE', 'Screening unavailable'), ('TRANSACTION_BLOCKED', 'Transaction blocked'), ('TRANSACTION_RELEASED', 'Transaction released'), ('CLINICAL_CONTEXT_STALE', 'Clinical context stale'), ('CLINICAL_CAPABILITY_DENIED', 'Clinical capability denied')], max_length=64),
        ),
    ]
