# Generated by Django 5.1.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0010_clinical_audit_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='posclinicalscreening',
            name='branch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='branch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='follow_up_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='patient_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='prescription_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='register_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='posclinicaldecision',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='posclinicaldecision',
            name='decision',
            field=models.CharField(
                choices=[
                    ('APPROVE', 'Approve'),
                    ('APPROVE_WITH_CONDITIONS', 'Approve with conditions'),
                    ('RETURN_FOR_CORRECTION', 'Return for correction'),
                    ('REJECT', 'Reject'),
                    ('CONTACT_PRESCRIBER', 'Contact prescriber'),
                    ('REQUIRE_ALTERNATIVE', 'Require alternative'),
                    ('REQUEST_MORE_INFORMATION', 'Request more information'),
                    ('APPROVE_AS_WRITTEN', 'Approve as written'),
                    ('APPROVE_WITH_COUNSELLING', 'Approve with counselling'),
                    ('REMOVE_MEDICINE', 'Remove medicine'),
                    ('CHANGE_QUANTITY', 'Change quantity'),
                    ('APPROVED_SUBSTITUTION', 'Approved substitution'),
                    ('PRESCRIBER_CLARIFICATION_REQUIRED', 'Prescriber clarification required'),
                    ('PATIENT_CLARIFICATION_REQUIRED', 'Patient clarification required'),
                    ('HOLD_TRANSACTION', 'Hold transaction'),
                    ('REJECT_SUPPLY', 'Reject supply'),
                    ('AUTHORIZED_OVERRIDE', 'Authorized override'),
                ],
                max_length=64,
            ),
        ),
    ]
