# Generated by Django 5.1.15 on 2026-07-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_override_idempotency_keys(apps, schema_editor):
    PosClinicalOverride = apps.get_model('cds', 'PosClinicalOverride')
    for override in PosClinicalOverride.objects.filter(idempotency_key__isnull=True).iterator():
        override.idempotency_key = f'legacy-override-{override.pk}'
        override.save(update_fields=['idempotency_key'])


def clear_override_idempotency_keys(apps, schema_editor):
    PosClinicalOverride = apps.get_model('cds', 'PosClinicalOverride')
    PosClinicalOverride.objects.filter(idempotency_key__startswith='legacy-override-').update(
        idempotency_key=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0011_pos_clinical_review_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posclinicaloverride',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='cds.posclinicaldecision'),
        ),
        migrations.AlterField(
            model_name='posclinicaloverride',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posclinicaloverride',
            name='clinical_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='posclinicaloverride',
            name='override_capability',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(model_name='posclinicaloverride', name='approved_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='posclinicaloverride', name='conditions', field=models.TextField(blank=True, default='')),
        migrations.AddField(model_name='posclinicaloverride', name='consumed_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='posclinicaloverride', name='consumed_event', field=models.CharField(blank=True, default='', max_length=128)),
        migrations.AddField(model_name='posclinicaloverride', name='consumed_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='posclinicaloverride', name='expires_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(
            model_name='posclinicaloverride',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(model_name='posclinicaloverride', name='rejected_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='posclinicaloverride', name='rejected_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='posclinicaloverride', name='rejection_reason', field=models.TextField(blank=True, default='')),
        migrations.AddField(model_name='posclinicaloverride', name='requested_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='posclinicaloverride', name='requested_reason', field=models.TextField(blank=True, default='')),
        migrations.AddField(model_name='posclinicaloverride', name='revocation_reason', field=models.TextField(blank=True, default='')),
        migrations.AddField(model_name='posclinicaloverride', name='revoked_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='posclinicaloverride', name='revoked_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='posclinicaloverride', name='scope', field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name='posclinicaloverride', name='status', field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CONDITIONS', 'Approved with conditions'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed')], default='REQUESTED', max_length=32)),
        migrations.AddField(model_name='posclinicaloverride', name='supporting_notes', field=models.TextField(blank=True, default='')),
        migrations.RunPython(
            backfill_override_idempotency_keys,
            clear_override_idempotency_keys,
        ),
        migrations.AlterField(
            model_name='posclinicaloverride',
            name='idempotency_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
