# Generated by Django 5.1.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0012_pos_clinical_override_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posclinicalauditevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('SCREENING_REQUESTED', 'Screening requested'),
                    ('SCREENING_COMPLETED', 'Screening completed'),
                    ('FINDING_DISPLAYED', 'Finding displayed'),
                    ('FINDING_ACKNOWLEDGED', 'Finding acknowledged'),
                    ('PHARMACIST_REVIEW_REQUESTED', 'Pharmacist review requested'),
                    ('PHARMACIST_AUTHENTICATED', 'Pharmacist authenticated'),
                    ('OVERRIDE_REQUESTED', 'Override requested'),
                    ('FINDING_RESOLVED', 'Finding resolved'),
                    ('OVERRIDE_RECORDED', 'Override recorded'),
                    ('OVERRIDE_REJECTED', 'Override rejected'),
                    ('OVERRIDE_REVOKED', 'Override revoked'),
                    ('OVERRIDE_EXPIRED', 'Override expired'),
                    ('OVERRIDE_CONSUMED', 'Override consumed'),
                    ('SCREENING_INVALIDATED', 'Screening invalidated'),
                    ('OFFLINE_SCREENING_USED', 'Offline screening used'),
                    ('SCREENING_UNAVAILABLE', 'Screening unavailable'),
                    ('TRANSACTION_BLOCKED', 'Transaction blocked'),
                    ('TRANSACTION_RELEASED', 'Transaction released'),
                    ('CLINICAL_CONTEXT_STALE', 'Clinical context stale'),
                    ('CLINICAL_CAPABILITY_DENIED', 'Clinical capability denied'),
                ],
                max_length=64,
            ),
        ),
    ]
