# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=40)),
                ('recipient', models.CharField(max_length=255)),
                ('template_code', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_notification_idempotency')],
            },
        ),
    ]
