# Generated by Django 5.1.15 on 2026-08-02 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenancy', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRolePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_code', models.CharField(help_text='e.g. platform.owner, compliance.officer, tenant.admin, pharmacist', max_length=40)),
                ('category', models.CharField(choices=[('DHA_UNAVAILABLE', 'DHA System Unavailable'), ('PPB_UNAVAILABLE', 'PPB System Unavailable'), ('HWR_UNAVAILABLE', 'DHA HWR System Unavailable'), ('OAUTH_TOKEN_EXPIRY', 'OAuth Token Expiry Warning'), ('OAUTH_REFRESH_FAILURE', 'OAuth Refresh Token Failure'), ('TLS_CERTIFICATE_EXPIRY', 'TLS Certificate Expiry Warning'), ('PROVIDER_CERTIFICATE_EXPIRY', 'Provider Client Certificate Expiry'), ('PREMISES_LICENCE_EXPIRY', 'Premises Licence Expiry Warning'), ('SUPERINTENDENT_LICENCE_EXPIRY', 'Superintendent Licence Expiry Warning'), ('PRACTITIONER_LICENCE_EXPIRY', 'Practitioner Licence Expiry Warning'), ('CONTROLLED_MEDICINE_AUTHORITY_EXPIRY', 'Controlled Medicine Authority Expiry'), ('INTEGRATION_ACTIVATION_PENDING', 'Integration Activation Request Pending'), ('INTEGRATION_ACTIVATION_APPROVED', 'Integration Activation Approved'), ('INTEGRATION_ACTIVATION_REJECTED', 'Integration Activation Rejected'), ('PROVIDER_CONNECTIVITY_RESTORED', 'Provider Connectivity Restored'), ('CIRCUIT_BREAKER_OPENED', 'Circuit Breaker Opened'), ('CIRCUIT_BREAKER_CLOSED', 'Circuit Breaker Closed'), ('RETRY_THRESHOLD_EXCEEDED', 'Retry Threshold Exceeded'), ('DEAD_LETTER_THRESHOLD_EXCEEDED', 'Dead Letter Queue Threshold Exceeded'), ('REGULATORY_RECALL_ACTIVATED', 'Regulatory Recall Activated'), ('REGULATORY_RECALL_ESCALATED', 'Regulatory Recall Escalated'), ('REGULATORY_RECALL_RELEASED', 'Regulatory Recall Released'), ('KILL_SWITCH_ACTIVATED', 'Emergency Provider Kill Switch Activated'), ('KILL_SWITCH_RELEASED', 'Emergency Provider Kill Switch Released')], max_length=60)),
                ('enabled_channels', models.JSONField(default=list, help_text='List of NotificationChannel values enabled for this role & category.')),
                ('minimum_severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Action Required'), ('EMERGENCY', 'Emergency System Alert')], default='INFO', max_length=20)),
            ],
            options={
                'unique_together': {('role_code', 'category')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('DHA_UNAVAILABLE', 'DHA System Unavailable'), ('PPB_UNAVAILABLE', 'PPB System Unavailable'), ('HWR_UNAVAILABLE', 'DHA HWR System Unavailable'), ('OAUTH_TOKEN_EXPIRY', 'OAuth Token Expiry Warning'), ('OAUTH_REFRESH_FAILURE', 'OAuth Refresh Token Failure'), ('TLS_CERTIFICATE_EXPIRY', 'TLS Certificate Expiry Warning'), ('PROVIDER_CERTIFICATE_EXPIRY', 'Provider Client Certificate Expiry'), ('PREMISES_LICENCE_EXPIRY', 'Premises Licence Expiry Warning'), ('SUPERINTENDENT_LICENCE_EXPIRY', 'Superintendent Licence Expiry Warning'), ('PRACTITIONER_LICENCE_EXPIRY', 'Practitioner Licence Expiry Warning'), ('CONTROLLED_MEDICINE_AUTHORITY_EXPIRY', 'Controlled Medicine Authority Expiry'), ('INTEGRATION_ACTIVATION_PENDING', 'Integration Activation Request Pending'), ('INTEGRATION_ACTIVATION_APPROVED', 'Integration Activation Approved'), ('INTEGRATION_ACTIVATION_REJECTED', 'Integration Activation Rejected'), ('PROVIDER_CONNECTIVITY_RESTORED', 'Provider Connectivity Restored'), ('CIRCUIT_BREAKER_OPENED', 'Circuit Breaker Opened'), ('CIRCUIT_BREAKER_CLOSED', 'Circuit Breaker Closed'), ('RETRY_THRESHOLD_EXCEEDED', 'Retry Threshold Exceeded'), ('DEAD_LETTER_THRESHOLD_EXCEEDED', 'Dead Letter Queue Threshold Exceeded'), ('REGULATORY_RECALL_ACTIVATED', 'Regulatory Recall Activated'), ('REGULATORY_RECALL_ESCALATED', 'Regulatory Recall Escalated'), ('REGULATORY_RECALL_RELEASED', 'Regulatory Recall Released'), ('KILL_SWITCH_ACTIVATED', 'Emergency Provider Kill Switch Activated'), ('KILL_SWITCH_RELEASED', 'Emergency Provider Kill Switch Released')], max_length=60)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Action Required'), ('EMERGENCY', 'Emergency System Alert')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('truth_label', models.CharField(default='MANUAL_INTERNAL_VERIFICATION', max_length=60)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notifications', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_notifications', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'severity', '-created_at'], name='ix_notif_tenant_sev'), models.Index(fields=['category', '-created_at'], name='ix_notif_cat_created')],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryExpiryTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('PREMISES_LICENCE', 'Pharmacy Premises Licence'), ('SUPERINTENDENT_LICENCE', 'Superintendent Pharmacist Licence'), ('PRACTITIONER_LICENCE', 'Practitioner Licence'), ('CONTROLLED_DRUG_AUTHORITY', 'Controlled Medicine Authority'), ('OAUTH_CREDENTIAL', 'OAuth Client Secret / Key'), ('PROVIDER_CERTIFICATE', 'TLS / Client Certificate')], max_length=40)),
                ('entity_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('expires_at', models.DateField()),
                ('last_notified_interval_days', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_evidence_reference', models.CharField(blank=True, max_length=250)),
                ('truth_label', models.CharField(default='MANUAL_INTERNAL_VERIFICATION', max_length=60)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_expiry_tracks', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['entity_type', 'expires_at'], name='ix_regexp_type_exp')],
            },
        ),
    ]
