# Generated by Django 5.1.15 on 2026-07-26 09:02

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPriceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_reference', models.CharField(max_length=120)),
                ('resolved_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason_code', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('price_type', models.CharField(choices=[('BASE', 'Base'), ('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('BRANCH_RETAIL', 'Branch retail'), ('BRANCH_WHOLESALE', 'Branch wholesale'), ('CUSTOMER_CONTRACT', 'Customer contract'), ('INSURANCE_TARIFF', 'Insurance tariff'), ('STAFF', 'Staff'), ('PROMOTIONAL', 'Promotional')], default='RETAIL', max_length=32)),
                ('scope_type', models.CharField(choices=[('TENANT', 'Tenant'), ('REGION', 'Region'), ('BRANCH_GROUP', 'Branch group'), ('BRANCH', 'Branch'), ('CUSTOMER_SEGMENT', 'Customer segment'), ('CUSTOMER', 'Customer'), ('INSURER', 'Insurer'), ('INSURANCE_PLAN', 'Insurance plan')], default='TENANT', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('rounding_policy', models.CharField(default='HALF_UP', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_books', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('TENANT', 'Tenant'), ('REGION', 'Region'), ('BRANCH_GROUP', 'Branch group'), ('BRANCH', 'Branch'), ('CUSTOMER_SEGMENT', 'Customer segment'), ('CUSTOMER', 'Customer'), ('INSURER', 'Insurer'), ('INSURANCE_PLAN', 'Insurance plan')], max_length=32)),
                ('branch_group', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('customer_segment', models.CharField(blank=True, default='', max_length=64)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('insurer_id', models.CharField(blank=True, default='', max_length=64)),
                ('insurance_plan_id', models.CharField(blank=True, default='', max_length=64)),
                ('priority', models.IntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_assignments', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_assignments', to='tenancy.tenant')),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pricing.pricebook')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceBookVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pricing.pricebook')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['price_book_id', '-version_number'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15)),
                ('maximum_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('minimum_allowed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pricing.pricebookversion')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AppliedPriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_reference', models.CharField(max_length=120)),
                ('line_type', models.CharField(default='SALE', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('source', models.CharField(max_length=40)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('resolution_trace', models.JSONField(blank=True, default=list)),
                ('context_hash', models.CharField(blank=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_prices', to='tenancy.tenant')),
                ('manual_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.manualpriceoverride')),
                ('price_book_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.pricebookversion')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='manualpriceoverride',
            index=models.Index(fields=['tenant', 'transaction_reference'], name='pricing_man_tenant__d501f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricebook',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_price_book_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='priceassignment',
            index=models.Index(fields=['tenant', 'scope_type', 'is_active'], name='pricing_pri_tenant__7ca839_idx'),
        ),
        migrations.AddIndex(
            model_name='priceassignment',
            index=models.Index(fields=['tenant', 'branch'], name='pricing_pri_tenant__c6e3d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricebookversion',
            constraint=models.UniqueConstraint(fields=('price_book', 'version_number'), name='uq_price_book_version_number'),
        ),
        migrations.AddConstraint(
            model_name='pricebookentry',
            constraint=models.UniqueConstraint(fields=('version', 'sku', 'minimum_quantity'), name='uq_price_entry_version_sku_band'),
        ),
        migrations.AddConstraint(
            model_name='pricebookentry',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_price_entry_nonneg'),
        ),
        migrations.AddIndex(
            model_name='appliedpricesnapshot',
            index=models.Index(fields=['tenant', 'sku', 'resolved_at'], name='pricing_app_tenant__724ee0_idx'),
        ),
        migrations.AddConstraint(
            model_name='appliedpricesnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'line_reference', 'line_type'), name='uq_applied_price_per_line'),
        ),
    ]
