# Generated by Django 5.1.15 on 2026-07-26 09:33

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('pricing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket_reference', models.CharField(max_length=120)),
                ('line_reference', models.CharField(max_length=120)),
                ('locked_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('context_hash', models.CharField(max_length=64)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated')], default='ACTIVE', max_length=20)),
                ('invalidation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_locks', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'basket_reference', 'status'], name='pricing_pri_tenant__31390d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tenant', 'basket_reference', 'line_reference'), name='uq_active_price_lock_per_line')],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
    ]
