# Generated by Django 5.1.15 on 2026-08-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Designated demonstration tenant. Permits the demo scenario engine to write synthetic data. Never set by migration; use designate_demo_tenant.'),
        ),
    ]
