# Generated by Django 5.1.15 on 2026-07-27 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('WINDOWS', 'Windows'), ('ANDROID', 'Android')], max_length=16)),
                ('version', models.CharField(max_length=40)),
                ('build_number', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('release_notes', models.TextField(blank=True)),
                ('minimum_os', models.CharField(blank=True, max_length=80)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['platform', '-build_number'],
                'indexes': [models.Index(fields=['platform', '-build_number'], name='ix_posrelease_latest')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'version'), name='uq_posrelease_platform_version'), models.UniqueConstraint(fields=('platform', 'build_number'), name='uq_posrelease_platform_build')],
            },
        ),
    ]
