# Generated by Django 5.1.15 on 2026-08-03 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('platform', '0002_posrelease_client_alignment'),
        ('tenancy', '0003_tenant_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenarioRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_name', models.CharField(max_length=120)),
                ('scenario_version', models.CharField(max_length=40)),
                ('profile', models.CharField(max_length=80)),
                ('random_seed', models.BigIntegerField()),
                ('as_of_date', models.DateField()),
                ('scale', models.CharField(default='small', max_length=20)),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('DRY_RUN_COMPLETE', 'Dry run complete'), ('APPROVED', 'Approved'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], db_index=True, default='PLANNED', max_length=20)),
                ('manifest_digest', models.CharField(blank=True, max_length=64)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('code_commit', models.CharField(blank=True, max_length=64)),
                ('migration_head', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='platform.demoscenariorun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_scenario_runs', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DemoScenarioObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=64)),
                ('generator', models.CharField(max_length=120)),
                ('seed_key', models.CharField(db_index=True, max_length=200)),
                ('branch_reference', models.CharField(blank=True, max_length=120)),
                ('reset_eligible', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_scenario_objects', to='tenancy.tenant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_created', to='platform.demoscenariorun')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DemoSeedApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_reason', models.TextField()),
                ('profile', models.CharField(max_length=80)),
                ('scenario_version', models.CharField(max_length=40)),
                ('random_seed', models.BigIntegerField()),
                ('as_of_date', models.DateField()),
                ('manifest_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('audit_correlation_id', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demo_seed_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_seed_requests', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='platform.demoscenariorun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_seed_approvals', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='demoscenariorun',
            index=models.Index(fields=['tenant', 'state'], name='ix_demorun_tenant_state'),
        ),
        migrations.AddConstraint(
            model_name='demoscenariorun',
            constraint=models.UniqueConstraint(fields=('tenant', 'profile', 'scenario_version', 'random_seed', 'as_of_date'), name='uniq_demo_run_plan'),
        ),
        migrations.AddIndex(
            model_name='demoscenarioobject',
            index=models.Index(fields=['tenant', 'content_type'], name='ix_demoobj_tenant_ct'),
        ),
        migrations.AddIndex(
            model_name='demoscenarioobject',
            index=models.Index(fields=['run', 'reset_eligible'], name='ix_demoobj_run_reset'),
        ),
        migrations.AddConstraint(
            model_name='demoscenarioobject',
            constraint=models.UniqueConstraint(fields=('run', 'content_type', 'object_id'), name='uniq_demo_object_per_run'),
        ),
        migrations.AddIndex(
            model_name='demoseedapproval',
            index=models.Index(fields=['tenant', 'status'], name='ix_demoappr_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='demoseedapproval',
            index=models.Index(fields=['manifest_digest'], name='ix_demoappr_digest'),
        ),
    ]
