# Generated by Django 5.1.15 on 2026-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_demo_scenario_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoscenarioobject',
            name='business_purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demoscenarioobject',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='demoscenarioobject',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='demoscenarioobject',
            name='relationship_group',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='demoscenarioobject',
            name='stage',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='demoscenarioobject',
            name='story_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='demoscenariorun',
            name='demo_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='demoscenariorun',
            name='stage_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
