FHIR_VERSION = "4.0.1"

# OperationOutcome Severity Levels
SEVERITY_FATAL = "fatal"
SEVERITY_ERROR = "error"
SEVERITY_WARNING = "warning"
SEVERITY_INFORMATION = "information"

# OperationOutcome Issue Codes (Subset of standard codes)
ISSUE_CODE_INVALID = "invalid"
ISSUE_CODE_STRUCTURE = "structure"
ISSUE_CODE_REQUIRED = "required"
ISSUE_CODE_VALUE = "value"
ISSUE_CODE_EXCEPTION = "exception"
ISSUE_CODE_SECURITY = "security"
ISSUE_CODE_FORBIDDEN = "forbidden"
ISSUE_CODE_NOT_FOUND = "not-found"
ISSUE_CODE_CONFLICT = "conflict"
ISSUE_CODE_MULTIPLE_MATCHES = "multiple-matches"
ISSUE_CODE_BUSINESS_RULE = "business-rule"
ISSUE_CODE_NOT_SUPPORTED = "not-supported"

# System URIs
SYSTEM_UUID = "urn:uuid:"
SYSTEM_TENANT_ID = "https://dawatrace.health/fhir/system/tenant-id"

# Permissions
PERMISSION_PATIENT_READ = "system/Patient.read"
PERMISSION_PATIENT_WRITE = "system/Patient.write"
PERMISSION_PRACTITIONER_READ = "system/Practitioner.read"
PERMISSION_PRACTITIONER_WRITE = "system/Practitioner.write"
PERMISSION_ORGANIZATION_READ = "system/Organization.read"
PERMISSION_LOCATION_READ = "system/Location.read"
PERMISSION_MEDICATION_READ = "system/Medication.read"
PERMISSION_MEDICATION_WRITE = "system/Medication.write"
PERMISSION_MEDICATIONREQUEST_READ = "system/MedicationRequest.read"
PERMISSION_MEDICATIONREQUEST_WRITE = "system/MedicationRequest.write"
PERMISSION_MEDICATIONDISPENSE_READ = "system/MedicationDispense.read"
PERMISSION_MEDICATIONDISPENSE_WRITE = "system/MedicationDispense.write"
PERMISSION_MEDICATIONSTATEMENT_READ = "system/MedicationStatement.read"
PERMISSION_MEDICATIONSTATEMENT_WRITE = "system/MedicationStatement.write"
PERMISSION_AUDITEVENT_READ = "system/AuditEvent.read"

PERMISSION_ALLERGYINTOLERANCE_READ = "system/AllergyIntolerance.read"
PERMISSION_ALLERGYINTOLERANCE_WRITE = "system/AllergyIntolerance.write"
PERMISSION_CONDITION_READ = "system/Condition.read"
PERMISSION_CONDITION_WRITE = "system/Condition.write"
PERMISSION_ENCOUNTER_READ = "system/Encounter.read"
PERMISSION_ENCOUNTER_WRITE = "system/Encounter.write"
PERMISSION_MEDICATIONADMINISTRATION_READ = "system/MedicationAdministration.read"
PERMISSION_MEDICATIONADMINISTRATION_WRITE = "system/MedicationAdministration.write"
PERMISSION_OBSERVATION_READ = "system/Observation.read"
PERMISSION_OBSERVATION_WRITE = "system/Observation.write"
PERMISSION_DIAGNOSTICREPORT_READ = "system/DiagnosticReport.read"
PERMISSION_DIAGNOSTICREPORT_WRITE = "system/DiagnosticReport.write"
PERMISSION_DOCUMENTREFERENCE_READ = "system/DocumentReference.read"
PERMISSION_DOCUMENTREFERENCE_WRITE = "system/DocumentReference.write"
PERMISSION_CODESYSTEM_READ = "system/CodeSystem.read"
PERMISSION_CODESYSTEM_WRITE = "system/CodeSystem.write"
PERMISSION_VALUESET_READ = "system/ValueSet.read"
PERMISSION_VALUESET_WRITE = "system/ValueSet.write"
PERMISSION_TERMINOLOGY_VALIDATE = "system/Terminology.validate"
PERMISSION_TERMINOLOGY_EXPAND = "system/Terminology.expand"
# Errors
SEVERITY_ERROR = "error"
