# Generated by Django 5.1.15 on 2026-07-22 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=160)),
                ('correlation_id', models.CharField(blank=True, max_length=160)),
                ('outcome', models.CharField(default='SUCCESS', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
