# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'model_name', 'object_id'], name='ix_audit_object'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'created_at'], name='ix_audit_created'),
        ),
    ]
