import type { IconName } from './icons.js';

export type ReportStatus = 'live' | 'preview' | 'planned';

export type ReportCategoryId =
  | 'executive'
  | 'sales'
  | 'procurement'
  | 'inventory'
  | 'finance'
  | 'quality'
  | 'clinical'
  | 'controlled'
  | 'regulatory'
  | 'logistics'
  | 'crm'
  | 'hr'
  | 'audit'
  | 'analytics'
  | 'security';

export interface ReportCategory {
  readonly id: ReportCategoryId;
  readonly label: string;
  readonly summary: string;
  readonly icon: IconName;
}

export interface ReportDefinition {
  readonly id: string;
  readonly category: ReportCategoryId;
  readonly name: string;
  readonly description: string;
  readonly audience: string;
  readonly cadence: string;
  readonly status: ReportStatus;
  /** In-app deep link when the report is backed by an HQ surface. */
  readonly href?: string;
  readonly metricLabel?: string;
}

export const REPORT_CATEGORIES: readonly ReportCategory[] = [
  { id: 'executive', label: 'Executive', summary: 'Board and leadership KPIs', icon: 'overview' },
  { id: 'sales', label: 'Sales & dispensing', summary: 'Till and prescription throughput', icon: 'store' },
  { id: 'procurement', label: 'Procurement', summary: 'Requisitions through returns', icon: 'inventory' },
  { id: 'inventory', label: 'Inventory', summary: 'Balances, FEFO and valuation', icon: 'inventory' },
  { id: 'finance', label: 'Finance', summary: 'Cash, AR/AP and profitability', icon: 'building' },
  { id: 'quality', label: 'Quality', summary: 'CAPA, recalls and quarantine', icon: 'shield' },
  { id: 'clinical', label: 'Clinical', summary: 'Screening, allergies and interventions', icon: 'clinical' },
  { id: 'controlled', label: 'Controlled drugs', summary: 'Register, issues and destruction', icon: 'security' },
  { id: 'regulatory', label: 'Regulatory', summary: 'PPB, GDP/GSP and PV', icon: 'docs' },
  { id: 'logistics', label: 'Logistics', summary: 'Shipments, POD and routes', icon: 'network' },
  { id: 'crm', label: 'CRM', summary: 'Customers and insurance use', icon: 'patients' },
  { id: 'hr', label: 'HR & operations', summary: 'Staff, tills and sync health', icon: 'users' },
  { id: 'audit', label: 'Audit', summary: 'Immutable activity and config', icon: 'shield' },
  { id: 'analytics', label: 'Analytics', summary: 'ABC/XYZ and forecasts', icon: 'activity' },
  { id: 'security', label: 'Security', summary: 'Access, threats and assurance', icon: 'security' },
];

/**
 * Enterprise reporting catalogue derived from
 * TibaTrace_Enterprise_Reporting_Catalogue.docx, extended with security reports
 * and mapped to live HQ surfaces where they already exist.
 */
export const REPORT_CATALOGUE: readonly ReportDefinition[] = [
  // 1. Executive
  {
    id: 'exec-dashboard',
    category: 'executive',
    name: 'Executive dashboard',
    description: 'Consolidated safety, stock, clinical and network signals for the active workspace.',
    audience: 'Leadership',
    cadence: 'Real-time',
    status: 'live',
    href: '#overview',
  },
  {
    id: 'exec-revenue',
    category: 'executive',
    name: 'Revenue summary',
    description: 'Sales and dispensing revenue roll-up by branch, channel and period.',
    audience: 'Finance / Leadership',
    cadence: 'Daily',
    status: 'preview',
    href: '#commerce',
    metricLabel: 'Open sales orders',
  },
  {
    id: 'exec-inventory-value',
    category: 'executive',
    name: 'Inventory value',
    description: 'On-hand stock valuation across locations and quality states.',
    audience: 'Finance / Operations',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
    metricLabel: 'Inventory batches',
  },
  {
    id: 'exec-cash-position',
    category: 'executive',
    name: 'Cash position',
    description: 'Open tills, expected drawers and unexplained variances.',
    audience: 'Finance',
    cadence: 'Intraday',
    status: 'live',
    href: '#cash',
    metricLabel: 'Open tills',
  },
  {
    id: 'exec-receivables',
    category: 'executive',
    name: 'Outstanding receivables',
    description: 'Customer and insurer balances awaiting settlement.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'preview',
    href: '#insurance',
  },
  {
    id: 'exec-payables',
    category: 'executive',
    name: 'Outstanding payables',
    description: 'Supplier liabilities from matched receipts and invoices.',
    audience: 'Finance / Procurement',
    cadence: 'Daily',
    status: 'preview',
    href: '#operations',
    metricLabel: 'Open purchase orders',
  },
  {
    id: 'exec-regulatory-alerts',
    category: 'executive',
    name: 'Regulatory alerts',
    description: 'Open compliance exceptions requiring management attention.',
    audience: 'Compliance',
    cadence: 'Daily',
    status: 'preview',
    href: '#governance',
  },
  {
    id: 'exec-quality-kpis',
    category: 'executive',
    name: 'Quality KPIs',
    description: 'Holds, releases, deviations and excursion indicators.',
    audience: 'Quality / Leadership',
    cadence: 'Weekly',
    status: 'preview',
    href: '#operations',
  },

  // 2. Sales & dispensing
  {
    id: 'sales-period',
    category: 'sales',
    name: 'Daily / weekly / monthly sales',
    description: 'Period sales totals with branch and tender breakdown.',
    audience: 'Commercial',
    cadence: 'Daily',
    status: 'preview',
    href: '#commerce',
  },
  {
    id: 'sales-by-branch',
    category: 'sales',
    name: 'Sales by branch',
    description: 'Comparative sales performance across network locations.',
    audience: 'Commercial',
    cadence: 'Daily',
    status: 'preview',
    href: '#network',
  },
  {
    id: 'sales-by-pharmacist',
    category: 'sales',
    name: 'Sales by pharmacist',
    description: 'Dispensing and verification throughput by licensed practitioner.',
    audience: 'Clinical ops',
    cadence: 'Daily',
    status: 'planned',
  },
  {
    id: 'sales-by-customer',
    category: 'sales',
    name: 'Sales by customer',
    description: 'Commercial customer order and fulfilment history.',
    audience: 'Commercial',
    cadence: 'On demand',
    status: 'live',
    href: '#people/customers',
    metricLabel: 'Customers',
  },
  {
    id: 'sales-by-insurer',
    category: 'sales',
    name: 'Sales by insurer',
    description: 'Insured dispensing volumes and claim values by payer.',
    audience: 'Insurance ops',
    cadence: 'Daily',
    status: 'live',
    href: '#insurance',
  },
  {
    id: 'sales-rx-dispensing',
    category: 'sales',
    name: 'Prescription dispensing',
    description: 'Prescription workflow states from intake through supply.',
    audience: 'Clinical ops',
    cadence: 'Real-time',
    status: 'live',
    href: '#clinical',
    metricLabel: 'Open prescriptions',
  },
  {
    id: 'sales-clinical-holds',
    category: 'sales',
    name: 'Clinical holds',
    description: 'Prescriptions paused for clinical or legal review.',
    audience: 'Clinical ops',
    cadence: 'Real-time',
    status: 'live',
    href: '#clinical',
  },
  {
    id: 'sales-clinical-overrides',
    category: 'sales',
    name: 'Clinical overrides',
    description: 'Recorded CDS and clinical screening overrides with rationale.',
    audience: 'Clinical governance',
    cadence: 'Daily',
    status: 'preview',
    href: '#clinical',
  },
  {
    id: 'sales-waiting-time',
    category: 'sales',
    name: 'Patient waiting time',
    description: 'Queue and turnaround times from prescription receipt to collection.',
    audience: 'Operations',
    cadence: 'Hourly',
    status: 'planned',
  },

  // 3. Procurement
  {
    id: 'proc-requisitions',
    category: 'procurement',
    name: 'Purchase requisitions',
    description: 'Raised, approved and fulfilled stock requests.',
    audience: 'Procurement',
    cadence: 'Daily',
    status: 'live',
    href: '#operations',
  },
  {
    id: 'proc-orders',
    category: 'procurement',
    name: 'Purchase orders',
    description: 'Open and closed POs with expected delivery and value.',
    audience: 'Procurement',
    cadence: 'Daily',
    status: 'live',
    href: '#operations',
    metricLabel: 'Open purchase orders',
  },
  {
    id: 'proc-grn',
    category: 'procurement',
    name: 'Goods receipts',
    description: 'GRNs, discrepancies and receipt completeness.',
    audience: 'Procurement / Warehouse',
    cadence: 'Daily',
    status: 'live',
    href: '#operations',
  },
  {
    id: 'proc-supplier-performance',
    category: 'procurement',
    name: 'Supplier performance',
    description: 'OTIF, quality holds and return rates by supplier.',
    audience: 'Procurement',
    cadence: 'Weekly',
    status: 'preview',
    href: '#operations',
  },
  {
    id: 'proc-lead-time',
    category: 'procurement',
    name: 'Lead time',
    description: 'Order-to-receipt lead times by supplier and SKU.',
    audience: 'Procurement',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'proc-price-variance',
    category: 'procurement',
    name: 'Price variance',
    description: 'PO versus invoice and catalogue price differences.',
    audience: 'Finance / Procurement',
    cadence: 'Weekly',
    status: 'preview',
    href: '#operations',
  },
  {
    id: 'proc-returns',
    category: 'procurement',
    name: 'Supplier returns',
    description: 'Returned batches and credit status.',
    audience: 'Procurement / Quality',
    cadence: 'Weekly',
    status: 'live',
    href: '#operations',
  },

  // 4. Inventory
  {
    id: 'inv-balance',
    category: 'inventory',
    name: 'Stock balance',
    description: 'On-hand, reserved and available quantities by location.',
    audience: 'Warehouse',
    cadence: 'Real-time',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'inv-batch',
    category: 'inventory',
    name: 'Batch inventory',
    description: 'Lot-level balances with expiry and quality state.',
    audience: 'Warehouse / Quality',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
    metricLabel: 'Inventory batches',
  },
  {
    id: 'inv-valuation',
    category: 'inventory',
    name: 'Inventory valuation',
    description: 'Financial valuation of stock by location and state.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'preview',
    href: '#inventory',
  },
  {
    id: 'inv-fefo',
    category: 'inventory',
    name: 'FEFO analysis',
    description: 'First-expiry-first-out compliance and reservation coverage.',
    audience: 'Warehouse',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'inv-expiry',
    category: 'inventory',
    name: 'Expiry report',
    description: 'Batches approaching or past expiry thresholds.',
    audience: 'Quality / Warehouse',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'inv-velocity',
    category: 'inventory',
    name: 'Slow / fast moving items',
    description: 'Movement velocity bands for replenishment planning.',
    audience: 'Procurement',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'inv-dead-stock',
    category: 'inventory',
    name: 'Dead stock',
    description: 'Items with no movement within the configured dormancy window.',
    audience: 'Commercial / Finance',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'inv-movements',
    category: 'inventory',
    name: 'Stock movements',
    description: 'Append-only ledger of receipts, issues, transfers and adjustments.',
    audience: 'Warehouse / Audit',
    cadence: 'On demand',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'inv-cycle-count',
    category: 'inventory',
    name: 'Cycle count variances',
    description: 'Count differences requiring investigation or write-off.',
    audience: 'Warehouse / Finance',
    cadence: 'Weekly',
    status: 'planned',
  },

  // 5. Finance
  {
    id: 'fin-gl',
    category: 'finance',
    name: 'General ledger',
    description: 'Posted financial movements for the reporting period.',
    audience: 'Finance',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'fin-trial-balance',
    category: 'finance',
    name: 'Trial balance',
    description: 'Debit and credit balances by account.',
    audience: 'Finance',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'fin-cash-book',
    category: 'finance',
    name: 'Cash book',
    description: 'Till and bank cash movements with shift linkage.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'fin-vat',
    category: 'finance',
    name: 'VAT report',
    description: 'Output and input tax summary for filing periods.',
    audience: 'Finance',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'fin-ar',
    category: 'finance',
    name: 'Accounts receivable',
    description: 'Ageing of customer and insurer receivables.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'preview',
    href: '#insurance',
  },
  {
    id: 'fin-ap',
    category: 'finance',
    name: 'Accounts payable',
    description: 'Ageing of supplier payables from matched invoices.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'preview',
    href: '#operations',
  },
  {
    id: 'fin-profitability',
    category: 'finance',
    name: 'Profitability',
    description: 'Margin analysis by branch, SKU class and payer mix.',
    audience: 'Leadership / Finance',
    cadence: 'Monthly',
    status: 'planned',
  },

  // 6. Quality
  {
    id: 'qa-capa',
    category: 'quality',
    name: 'CAPA',
    description: 'Corrective and preventive actions with ageing and owners.',
    audience: 'Quality',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'qa-deviations',
    category: 'quality',
    name: 'Deviations',
    description: 'Recorded process and product deviations.',
    audience: 'Quality',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'qa-recalls',
    category: 'quality',
    name: 'Recalls',
    description: 'Active and historical recall actions with batch impact.',
    audience: 'Quality / Regulatory',
    cadence: 'On demand',
    status: 'preview',
    href: '#catalogue',
  },
  {
    id: 'qa-temperature',
    category: 'quality',
    name: 'Temperature excursions',
    description: 'Cold-chain and storage excursions tied to received batches.',
    audience: 'Quality',
    cadence: 'Daily',
    status: 'preview',
    href: '#operations',
  },
  {
    id: 'qa-quarantine',
    category: 'quality',
    name: 'Quarantine stock',
    description: 'Batches held pending inspection or investigation.',
    audience: 'Quality / Warehouse',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'qa-released',
    category: 'quality',
    name: 'Released stock',
    description: 'Quality-released batches available for sale or dispensing.',
    audience: 'Quality',
    cadence: 'Daily',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'qa-supplier',
    category: 'quality',
    name: 'Supplier quality',
    description: 'Qualification status and quality performance by supplier.',
    audience: 'Quality / Procurement',
    cadence: 'Monthly',
    status: 'live',
    href: '#operations',
  },

  // 7. Clinical
  {
    id: 'clin-interactions',
    category: 'clinical',
    name: 'Drug interactions',
    description: 'Screening findings for interacting therapies.',
    audience: 'Clinical governance',
    cadence: 'Daily',
    status: 'preview',
    href: '#clinical',
  },
  {
    id: 'clin-screening',
    category: 'clinical',
    name: 'Clinical screening outcomes',
    description: 'CDS outcomes against published knowledge releases.',
    audience: 'Clinical governance',
    cadence: 'Daily',
    status: 'live',
    href: '#clinical',
    metricLabel: 'Active clinical releases',
  },
  {
    id: 'clin-overrides',
    category: 'clinical',
    name: 'Override reports',
    description: 'Pharmacist overrides with reason codes and audit linkage.',
    audience: 'Clinical governance',
    cadence: 'Daily',
    status: 'preview',
    href: '#clinical',
  },
  {
    id: 'clin-allergy',
    category: 'clinical',
    name: 'Allergy alerts',
    description: 'Allergy-related screening alerts and acknowledgements.',
    audience: 'Clinical ops',
    cadence: 'Daily',
    status: 'preview',
    href: '#clinical',
  },
  {
    id: 'clin-interventions',
    category: 'clinical',
    name: 'Pharmacist interventions',
    description: 'Documented clinical interventions during dispensing.',
    audience: 'Clinical governance',
    cadence: 'Weekly',
    status: 'planned',
  },

  // 8. Controlled drugs
  {
    id: 'cd-register',
    category: 'controlled',
    name: 'Controlled drug register',
    description: 'Running register of controlled substance balances.',
    audience: 'Pharmacist in charge',
    cadence: 'Daily',
    status: 'planned',
  },
  {
    id: 'cd-receipts',
    category: 'controlled',
    name: 'Controlled drug receipts',
    description: 'Inbound controlled stock with witness and documentation.',
    audience: 'Pharmacist in charge',
    cadence: 'On demand',
    status: 'planned',
  },
  {
    id: 'cd-issues',
    category: 'controlled',
    name: 'Controlled drug issues',
    description: 'Dispensed and issued controlled quantities.',
    audience: 'Pharmacist in charge',
    cadence: 'Daily',
    status: 'planned',
  },
  {
    id: 'cd-destruction',
    category: 'controlled',
    name: 'Controlled drug destruction',
    description: 'Destruction events with authorisation trail.',
    audience: 'Compliance',
    cadence: 'On demand',
    status: 'planned',
  },
  {
    id: 'cd-audit',
    category: 'controlled',
    name: 'Controlled drug audit trail',
    description: 'Immutable trail of controlled stock actions.',
    audience: 'Audit / Compliance',
    cadence: 'On demand',
    status: 'preview',
    href: '#governance',
  },

  // 9. Regulatory
  {
    id: 'reg-ppb',
    category: 'regulatory',
    name: 'PPB reports',
    description: 'Exports aligned to Pharmacy and Poisons Board reporting needs.',
    audience: 'Regulatory',
    cadence: 'Periodic',
    status: 'planned',
  },
  {
    id: 'reg-traceability',
    category: 'regulatory',
    name: 'Batch traceability',
    description: 'Forward and backward batch genealogy across supply and dispensing.',
    audience: 'Quality / Regulatory',
    cadence: 'On demand',
    status: 'preview',
    href: '#inventory',
  },
  {
    id: 'reg-gdp-gsp',
    category: 'regulatory',
    name: 'GDP / GSP compliance',
    description: 'Good distribution and storage practice indicators.',
    audience: 'Compliance',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'reg-pv',
    category: 'regulatory',
    name: 'Pharmacovigilance',
    description: 'Adverse event and safety signal reporting package.',
    audience: 'Clinical / Regulatory',
    cadence: 'On demand',
    status: 'planned',
  },

  // 10. Logistics
  {
    id: 'log-shipments',
    category: 'logistics',
    name: 'Shipment tracking',
    description: 'Outbound shipment status across the fulfilment network.',
    audience: 'Logistics',
    cadence: 'Real-time',
    status: 'live',
    href: '#commerce',
  },
  {
    id: 'log-delivery',
    category: 'logistics',
    name: 'Delivery performance',
    description: 'On-time delivery and failed-attempt rates.',
    audience: 'Logistics',
    cadence: 'Weekly',
    status: 'preview',
    href: '#commerce',
  },
  {
    id: 'log-pod',
    category: 'logistics',
    name: 'POD status',
    description: 'Proof-of-delivery capture and exceptions.',
    audience: 'Logistics',
    cadence: 'Daily',
    status: 'preview',
    href: '#commerce',
  },
  {
    id: 'log-routes',
    category: 'logistics',
    name: 'Route performance',
    description: 'Route utilisation and stop-level outcomes.',
    audience: 'Logistics',
    cadence: 'Weekly',
    status: 'planned',
  },

  // 11. CRM
  {
    id: 'crm-growth',
    category: 'crm',
    name: 'Customer growth',
    description: 'New, active and dormant commercial customer trends.',
    audience: 'Commercial',
    cadence: 'Monthly',
    status: 'preview',
    href: '#people/customers',
    metricLabel: 'Customers',
  },
  {
    id: 'crm-patient-history',
    category: 'crm',
    name: 'Patient purchase history',
    description: 'Patient-linked dispensing history for continuity of care.',
    audience: 'Clinical ops',
    cadence: 'On demand',
    status: 'live',
    href: '#people/patients',
    metricLabel: 'Patients',
  },
  {
    id: 'crm-insurance-util',
    category: 'crm',
    name: 'Insurance utilization',
    description: 'Member utilisation and benefit consumption by insurer.',
    audience: 'Insurance ops',
    cadence: 'Monthly',
    status: 'live',
    href: '#insurance',
  },

  // 12. HR & operations
  {
    id: 'hr-productivity',
    category: 'hr',
    name: 'Staff productivity',
    description: 'Operator throughput across dispensing and till activities.',
    audience: 'Operations',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'hr-register-sessions',
    category: 'hr',
    name: 'Register sessions',
    description: 'Open and closed till sessions by operator and register.',
    audience: 'Finance / Operations',
    cadence: 'Intraday',
    status: 'live',
    href: '#cash',
    metricLabel: 'Open tills',
  },
  {
    id: 'hr-x-reports',
    category: 'hr',
    name: 'X reports',
    description: 'Interim till readings without closing the session.',
    audience: 'Finance',
    cadence: 'On demand',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'hr-z-reports',
    category: 'hr',
    name: 'Z reports',
    description: 'End-of-day till closures with declared cash and variance.',
    audience: 'Finance',
    cadence: 'Daily',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'hr-cash-variance',
    category: 'hr',
    name: 'Cash variance',
    description: 'Unexplained drawer differences requiring explanation.',
    audience: 'Finance / Audit',
    cadence: 'Daily',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'hr-offline',
    category: 'hr',
    name: 'Offline transactions',
    description: 'Transactions captured while offline awaiting sync.',
    audience: 'Operations / IT',
    cadence: 'Intraday',
    status: 'planned',
  },
  {
    id: 'hr-sync-failures',
    category: 'hr',
    name: 'Sync failures',
    description: 'Failed device and branch synchronisation attempts.',
    audience: 'IT',
    cadence: 'Intraday',
    status: 'preview',
    href: '#governance',
  },

  // 13. Audit
  {
    id: 'audit-user',
    category: 'audit',
    name: 'User audit trail',
    description: 'Immutable user activity across governed HQ and POS actions.',
    audience: 'Audit / Security',
    cadence: 'On demand',
    status: 'live',
    href: '#governance',
  },
  {
    id: 'audit-financial',
    category: 'audit',
    name: 'Financial audit',
    description: 'Cash, pricing and settlement actions with actor attribution.',
    audience: 'Audit / Finance',
    cadence: 'On demand',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'audit-inventory',
    category: 'audit',
    name: 'Inventory audit',
    description: 'Stock ledger and adjustment audit package.',
    audience: 'Audit / Warehouse',
    cadence: 'On demand',
    status: 'live',
    href: '#inventory',
  },
  {
    id: 'audit-clinical',
    category: 'audit',
    name: 'Clinical audit',
    description: 'Screening, override and dispensing clinical decisions.',
    audience: 'Clinical governance',
    cadence: 'On demand',
    status: 'live',
    href: '#clinical',
  },
  {
    id: 'audit-config',
    category: 'audit',
    name: 'Configuration changes',
    description: 'Changes to roles, pricing, catalogue selection and tenant settings.',
    audience: 'Audit / Security',
    cadence: 'On demand',
    status: 'preview',
    href: '#governance',
  },

  // 14. Analytics
  {
    id: 'an-abc-xyz',
    category: 'analytics',
    name: 'ABC / XYZ analysis',
    description: 'Value and demand-variability classification of the catalogue.',
    audience: 'Procurement / Commercial',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'an-demand-forecast',
    category: 'analytics',
    name: 'Demand forecast',
    description: 'Forward demand estimate by SKU and branch.',
    audience: 'Procurement',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'an-inventory-forecast',
    category: 'analytics',
    name: 'Inventory forecast',
    description: 'Projected stock cover and replenishment need.',
    audience: 'Operations',
    cadence: 'Weekly',
    status: 'planned',
  },
  {
    id: 'an-revenue-forecast',
    category: 'analytics',
    name: 'Revenue forecast',
    description: 'Projected revenue by branch and channel.',
    audience: 'Leadership',
    cadence: 'Monthly',
    status: 'planned',
  },
  {
    id: 'an-basket',
    category: 'analytics',
    name: 'Basket analysis',
    description: 'Co-purchase patterns across dispensing and OTC sales.',
    audience: 'Commercial',
    cadence: 'Monthly',
    status: 'planned',
  },

  // 15. Security (extension beyond the catalogue DOCX)
  {
    id: 'sec-access-grants',
    category: 'security',
    name: 'User access & role grants',
    description: 'Active accounts, role assignments and account status changes.',
    audience: 'Security / Identity',
    cadence: 'On demand',
    status: 'live',
    href: '#access',
    metricLabel: 'Active users',
  },
  {
    id: 'sec-capability-matrix',
    category: 'security',
    name: 'Capability coverage matrix',
    description: 'Role × capability grants for tenant authority review.',
    audience: 'Security / Identity',
    cadence: 'On demand',
    status: 'live',
    href: '#access',
  },
  {
    id: 'sec-permission-changes',
    category: 'security',
    name: 'Permission change report',
    description: 'Recent role capability and user-role grant mutations.',
    audience: 'Security',
    cadence: 'Daily',
    status: 'preview',
    href: '#access',
  },
  {
    id: 'sec-service-accounts',
    category: 'security',
    name: 'Service account credentials',
    description: 'Machine identities, fingerprints and granted capabilities.',
    audience: 'Security / IT',
    cadence: 'Weekly',
    status: 'live',
    href: '#access',
  },
  {
    id: 'sec-session-assurance',
    category: 'security',
    name: 'Session & authentication assurance',
    description: 'Authenticated HQ sessions, password resets and suspended accounts.',
    audience: 'Security',
    cadence: 'Daily',
    status: 'live',
    href: '#access',
  },
  {
    id: 'sec-audit-trail',
    category: 'security',
    name: 'Security audit trail',
    description: 'Immutable security-relevant audit events and failed domain events.',
    audience: 'Security / Audit',
    cadence: 'On demand',
    status: 'live',
    href: '#governance',
  },
  {
    id: 'sec-tenant-isolation',
    category: 'security',
    name: 'Tenant isolation posture',
    description: 'Cross-tenant boundary checks, scoped queries and isolation exceptions.',
    audience: 'Security / Platform',
    cadence: 'Release',
    status: 'preview',
    href: '#governance',
  },
  {
    id: 'sec-fhir-idempotency',
    category: 'security',
    name: 'FHIR exchange integrity',
    description: 'Idempotent FHIR writes, duplicate protection and actor attribution.',
    audience: 'Security / Interop',
    cadence: 'Daily',
    status: 'live',
    href: '#clinical',
    metricLabel: 'FHIR idempotency records',
  },
  {
    id: 'sec-forced-closures',
    category: 'security',
    name: 'Forced register closures',
    description: 'Till closures performed outside the accountable operator path.',
    audience: 'Security / Finance',
    cadence: 'Daily',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'sec-cash-exceptions',
    category: 'security',
    name: 'Cash exception reviews',
    description: 'Variance investigations opened, under review and resolved.',
    audience: 'Security / Finance',
    cadence: 'Daily',
    status: 'live',
    href: '#cash',
  },
  {
    id: 'sec-clinical-authz',
    category: 'security',
    name: 'Clinical authorisation denials',
    description: 'Capability-denied clinical actions and override authentication events.',
    audience: 'Security / Clinical',
    cadence: 'Daily',
    status: 'preview',
    href: '#clinical',
  },
  {
    id: 'sec-document-access',
    category: 'security',
    name: 'Document access & integrity',
    description: 'Document downloads, hash verification outcomes and token-bound access.',
    audience: 'Security',
    cadence: 'Weekly',
    status: 'preview',
    href: '#governance',
  },
  {
    id: 'sec-dependency-posture',
    category: 'security',
    name: 'Dependency & vulnerability posture',
    description: 'Advisory scan status for Python/npm dependencies and container images.',
    audience: 'Security / Engineering',
    cadence: 'Release',
    status: 'planned',
  },
  {
    id: 'sec-secret-scan',
    category: 'security',
    name: 'Secret scan findings',
    description: 'Source-tree secret scan baseline and outstanding findings.',
    audience: 'Security',
    cadence: 'Release',
    status: 'planned',
  },
];

export function reportStatusLabel(status: ReportStatus): string {
  if (status === 'live') return 'Live';
  if (status === 'preview') return 'Linked preview';
  return 'Catalogue';
}
