# Generated by Django 5.1.15 on 2026-07-26 03:38

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('state', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('REOPENED_BY_EXCEPTION', 'Reopened by exception')], default='OPEN', max_length=30)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_days', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_days', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-business_date'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PosRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('printer_config', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('state', models.CharField(choices=[('UNCONFIGURED', 'Unconfigured'), ('AVAILABLE', 'Available'), ('OPEN', 'Open'), ('LOCKED', 'Locked'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('OFFLINE', 'Offline'), ('SUSPENDED', 'Suspended'), ('OUT_OF_SERVICE', 'Out of service')], default='UNCONFIGURED', max_length=20)),
                ('expected_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_synchronised_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_registers', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_registers', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('forced_closure', models.BooleanField(default=False)),
                ('forced_closure_reason', models.TextField(blank=True, default='')),
                ('business_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_sessions', to='pos_shift.businessday')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos_shift.posregister')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_sessions', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperatorShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('HANDOVER_REQUESTED', 'Handover requested'), ('CLOSED', 'Closed'), ('FORCE_CLOSED', 'Force closed')], default='OPEN', max_length=25)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handed_over_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_shifts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_shifts', to='tenancy.tenant')),
                ('register_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_shifts', to='pos_shift.registersession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CASH_IN', 'Cash in'), ('CASH_OUT', 'Cash out'), ('FLOAT_TOP_UP', 'Float top-up'), ('SAFE_DROP', 'Safe drop'), ('PETTY_CASH', 'Petty cash'), ('BANKING', 'Banking'), ('CORRECTION', 'Correction'), ('OTHER_AUTHORISED_MOVEMENT', 'Other authorised movement')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('reason_code', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='tenancy.tenant')),
                ('operator_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='pos_shift.operatorshift')),
                ('register_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='pos_shift.registersession')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing')], max_length=10)),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('denominations', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_declarations', to='tenancy.tenant')),
                ('operator_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_declarations', to='pos_shift.operatorshift')),
                ('register_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_declarations', to='pos_shift.registersession')),
            ],
            options={
                'ordering': ['register_session_id', 'kind', 'attempt'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='businessday',
            constraint=models.UniqueConstraint(fields=('tenant', 'location', 'business_date'), name='uq_business_day_tenant_loc_date'),
        ),
        migrations.AddConstraint(
            model_name='posregister',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_pos_register_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='registersession',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['OPEN', 'CLOSING'])), fields=('register',), name='uq_register_one_active_session'),
        ),
        migrations.AddConstraint(
            model_name='operatorshift',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['OPEN', 'HANDOVER_REQUESTED'])), fields=('register_session',), name='uq_session_one_active_shift'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_cash_movement_amount_positive'),
        ),
    ]
