# Generated by Django 5.1.15 on 2026-07-26 03:52

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_shift', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('X', 'X report (interim)'), ('Z', 'Z report (final closure)')], max_length=1)),
                ('report_number', models.CharField(max_length=120)),
                ('sequence', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closure_type', models.CharField(choices=[('NORMAL', 'Normal'), ('FORCED', 'Forced closure')], default='NORMAL', max_length=10)),
                ('closure_reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reports', to='pos_shift.businessday')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='pos_shift.operatorshift')),
                ('register_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='pos_shift.registersession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_reports', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftReportReprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy_number', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('reprinted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('printer', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprints', to='pos_shift.shiftreport')),
                ('reprinted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reprints', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['report_id', 'copy_number'],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.UniqueConstraint(fields=('tenant', 'report_number'), name='uq_shift_report_tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='shiftreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'Z')), fields=('register_session',), name='uq_register_session_single_z'),
        ),
        migrations.AddConstraint(
            model_name='shiftreportreprint',
            constraint=models.UniqueConstraint(fields=('report', 'copy_number'), name='uq_report_reprint_copy'),
        ),
    ]
