# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_reference_id', models.CharField(max_length=255)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('emergency_contact', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen_name', models.CharField(max_length=160)),
                ('allergen_code', models.CharField(blank=True, max_length=100)),
                ('allergen_system', models.CharField(blank=True, max_length=255)),
                ('reaction', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HARD_STOP', 'Hard stop')], default='WARNING', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('directions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=16)),
                ('effective_start', models.DateTimeField(blank=True, null=True)),
                ('effective_end', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_statements', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'verification_status'], name='ix_patient_verify_tenant'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='ix_patient_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('tenant', 'internal_reference_id'), name='uq_patient_reference_tenant'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['tenant', 'patient', 'is_active'], name='ix_patient_allergy_active'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['tenant', 'allergen_name'], name='ix_patient_allergen'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(fields=('tenant', 'system', 'value'), name='uq_patient_identifier_tenant'),
        ),
    ]
