# Generated by Django 5.1.15 on 2026-07-24 18:45

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_clinicalfinding_clinical_category_and_more'),
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientClinicalSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregnancy_status', models.CharField(default='NOT_RECORDED', max_length=40)),
                ('lactation_status', models.CharField(default='NOT_RECORDED', max_length=40)),
                ('renal_impairment', models.CharField(default='NOT_RECORDED', max_length=40)),
                ('hepatic_impairment', models.CharField(default='NOT_RECORDED', max_length=40)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source', models.CharField(default='NOT_RECORDED', max_length=120)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PATIENT_REPORTED', 'Patient reported'), ('CLINICIAN_VERIFIED', 'Clinician verified')], default='UNVERIFIED', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientConditionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='', max_length=120)),
                ('code_system', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=120)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=30)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='patientidentifier',
            name='uq_patient_identifier_tenant',
        ),
        migrations.AddField(
            model_name='patient',
            name='communication_preference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_status',
            field=models.CharField(default='NOT_RECORDED', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='external_patient_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_or_caregiver',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='patient',
            name='record_restrictions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='active_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cds.activeingredient'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='medicinal_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='onset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='source',
            field=models.CharField(default='PATIENT_REPORTED', max_length=120),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='status',
            field=models.CharField(choices=[('SUSPECTED', 'Suspected'), ('CONFIRMED', 'Confirmed'), ('REFUTED', 'Refuted'), ('INACTIVE', 'Inactive')], default='SUSPECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PATIENT_REPORTED', 'Patient reported'), ('CLINICIAN_VERIFIED', 'Clinician verified')], default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='identifier_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth certificate'), ('HOSPITAL_NUMBER', 'Hospital number'), ('INSURANCE_NUMBER', 'Insurance number'), ('REFUGEE_ID', 'Refugee ID'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='issuing_authority',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='last_four',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='protected_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='value_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='patientidentifier',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientidentifier',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('patient_number', ''), _negated=True), fields=('tenant', 'patient_number'), name='uq_patient_number_tenant'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('external_patient_reference', ''), _negated=True), fields=('tenant', 'external_patient_reference'), name='uq_patient_external_ref_tenant'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('value_hash', ''), _negated=True), fields=('tenant', 'identifier_type', 'value_hash'), name='uq_patient_identifier_hash'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('value', ''), _negated=True), fields=('tenant', 'system', 'value'), name='uq_patient_identifier_tenant'),
        ),
        migrations.AddField(
            model_name='patientclinicalsummary',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_summary', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientclinicalsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='patientclinicalsummary',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientconditionsummary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_summaries', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientconditionsummary',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientconditionsummary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='patientclinicalsummary',
            constraint=models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='chk_patient_height_positive'),
        ),
        migrations.AddConstraint(
            model_name='patientclinicalsummary',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gt', 0), _connector='OR'), name='chk_patient_weight_positive'),
        ),
        migrations.AddIndex(
            model_name='patientconditionsummary',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='ix_patient_condition_active'),
        ),
    ]
