# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('source_environment', models.CharField(max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyIdentifierCrosswalk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_entity_type', models.CharField(max_length=120)),
                ('source_identifier', models.CharField(max_length=255)),
                ('target_entity_type', models.CharField(max_length=120)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('migration_batch', models.CharField(max_length=120)),
                ('immutable_metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_crosswalks', to='tenancy.tenant')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crosswalks', to='crosswalks.legacysystem')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'target_entity_type', 'target_uuid'], name='ix_crosswalk_target'), models.Index(fields=['tenant', 'migration_batch'], name='ix_crosswalk_batch')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_system', 'source_entity_type', 'source_identifier'), name='uq_crosswalk_source_tenant')],
            },
        ),
    ]
