# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PractitionerIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='practitioners.practitioner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PractitionerLicence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_number', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='VALID', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='practitioners.practitioner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PractitionerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_code', models.CharField(max_length=100)),
                ('specialty_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_roles', to='organizations.organization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='practitioners.practitioner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['tenant', 'status', 'last_name'], name='ix_practitioner_tenant'),
        ),
        migrations.AddConstraint(
            model_name='practitioneridentifier',
            constraint=models.UniqueConstraint(fields=('tenant', 'system', 'value'), name='uq_practitioner_identifier_tenant'),
        ),
        migrations.AddConstraint(
            model_name='practitionerlicence',
            constraint=models.UniqueConstraint(fields=('tenant', 'issuer', 'licence_number'), name='uq_practitioner_licence_tenant'),
        ),
        migrations.AddConstraint(
            model_name='practitionerrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'practitioner', 'organization', 'role_code'), name='uq_practitioner_role_scope'),
        ),
    ]
