# Generated by Django 5.1.15 on 2026-07-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='controlled_medicine_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='licence_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='licence_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='licence_status',
            field=models.CharField(default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='licensing_body',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='prescribing_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='profession',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('DENTIST', 'Dentist'), ('CLINICAL_OFFICER', 'Clinical officer'), ('NURSE_PRESCRIBER', 'Nurse prescriber'), ('VETERINARY_PRESCRIBER', 'Veterinary prescriber'), ('OTHER_AUTHORIZED_PRESCRIBER', 'Other authorized prescriber')], default='OTHER_AUTHORIZED_PRESCRIBER', max_length=50),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='professional_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='verification_state',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('MANUAL_REVIEW', 'Manual review')], default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='controlled_medicine_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='prescribing_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='verification_state',
            field=models.CharField(default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitionerlicence',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('tenant', 'registration_number'), name='uq_practitioner_registration'),
        ),
    ]
