# Generated by Django 5.1.15 on 2026-08-02 07:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('STOCK_QUARANTINE', 'Stock quarantined'), ('PATIENT_CONTACT', 'Patient contact initiated'), ('PRODUCT_RETURN', 'Product returned to supplier'), ('DESTRUCTION', 'Product destroyed'), ('REGULATORY_REPORT', 'Regulatory report submitted'), ('STOCK_RELEASE', 'Stock released (post-clearance)')], max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_reference', models.CharField(help_text='PPB or regulator-assigned reference number.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical safety recall'), ('HIGH', 'High priority alert'), ('MEDIUM', 'Medium priority alert'), ('LOW', 'Low priority / informational')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('WITHDRAWN', 'Withdrawn by regulator'), ('SUPERSEDED', 'Superseded by newer alert')], default='DRAFT', max_length=20)),
                ('issuing_regulator', models.CharField(default='PPB', max_length=80)),
                ('regulator_issue_date', models.DateField(blank=True, null=True)),
                ('ppb_registration_number', models.CharField(blank=True, max_length=80)),
                ('gtin', models.CharField(blank=True, max_length=14)),
                ('product_name', models.CharField(blank=True, max_length=300)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200)),
                ('affected_batches', models.JSONField(default=list, help_text='List of batch number strings.')),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('truth_label', models.CharField(default='LOCAL_RECALL_WORKFLOW_NO_REGULATOR_FEED', max_length=60)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_regulatory_alerts', to=settings.AUTH_USER_MODEL)),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingested_regulatory_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryAlertVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recalls.regulatoryalert')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_alert_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('truth_label', models.CharField(default='LOCAL_RECALL_WORKFLOW_NO_REGULATOR_FEED', max_length=60)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='recalls.regulatoryaction')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_code', models.CharField(blank=True, max_length=120)),
                ('ppb_registration_number', models.CharField(blank=True, max_length=80)),
                ('gtin', models.CharField(blank=True, max_length=14)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('confidence_tier', models.CharField(choices=[('GTIN_EXACT', 'GS1 GTIN exact match'), ('PPB_REGISTRATION_EXACT', 'PPB registration number exact match'), ('PRODUCT_MANUFACTURER_MATCH', 'Product + manufacturer match (review required)'), ('BATCH_NUMBER_MATCH', 'Batch number match'), ('MANUAL_REVIEW', 'Manual review required')], default='MANUAL_REVIEW', max_length=40)),
                ('requires_manual_review', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='recalls.regulatoryalert')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_match_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['confidence_tier', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryTenantImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending assessment'), ('QUARANTINED', 'Stock quarantined'), ('UNDER_REVIEW', 'Under compliance review'), ('RESOLVED', 'Resolved'), ('RELEASED', 'Released (regulator withdrawal confirmed)'), ('NOT_AFFECTED', 'Not affected')], default='PENDING', max_length=20)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('affected_batches', models.JSONField(default=list)),
                ('quarantined_stock_count', models.IntegerField(default=0)),
                ('prior_dispense_trace_required', models.BooleanField(default=False)),
                ('prior_dispense_patient_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_impacts', to='recalls.regulatoryalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_impacts', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('regulator_withdrawal_reference', models.CharField(blank=True, max_length=200)),
                ('compliance_review_notes', models.TextField()),
                ('truth_label', models.CharField(default='LOCAL_RECALL_WORKFLOW_NO_REGULATOR_FEED', max_length=60)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_closures', to=settings.AUTH_USER_MODEL)),
                ('impact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='recalls.regulatorytenantimpact')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.AddField(
            model_name='regulatoryaction',
            name='impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recalls.regulatorytenantimpact'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['status', '-ingested_at'], name='ix_regalert_status'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['ppb_registration_number'], name='ix_regalert_ppb_reg'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['gtin'], name='ix_regalert_gtin'),
        ),
        migrations.AlterUniqueTogether(
            name='regulatoryalertversion',
            unique_together={('alert', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='regulatorytenantimpact',
            unique_together={('alert', 'tenant')},
        ),
    ]
