# Generated by Django 5.1.15 on 2026-08-02 07:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10)),
                ('message_type', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('IN_FLIGHT', 'In flight'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('DEAD_LETTERED', 'Dead-lettered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payload_digest', models.CharField(help_text='SHA-256 hex digest of the payload. Payload itself is not stored.', max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_messages', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('evidence_payload', models.JSONField(default=dict)),
                ('truth_label', models.CharField(default='ADAPTER_SCAFFOLDED_NOT_CONNECTED', max_length=60)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='integrations.integrationmessage')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dead_lettered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dead_letter_reason', models.TextField()),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_notes', models.TextField(blank=True)),
                ('replayed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replayed_dead_letters', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='integrations.integrationmessage')),
            ],
            options={
                'ordering': ['-dead_lettered_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField()),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('retry_after_seconds', models.IntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='integrations.integrationmessage')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderActivationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('SANDBOX_CONFIGURED', 'Sandbox configured'), ('SANDBOX_TESTING', 'Sandbox testing'), ('SANDBOX_PASSED', 'Sandbox passed'), ('SECURITY_APPROVED', 'Security approved'), ('PRODUCTION_APPROVED', 'Production approved'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('DECOMMISSIONED', 'Decommissioned')], default='REQUESTED', max_length=30)),
                ('justification', models.TextField()),
                ('sandbox_evidence', models.JSONField(blank=True, default=dict)),
                ('security_review_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_activation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderActivationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('decision_notes', models.TextField(blank=True)),
                ('truth_label', models.CharField(default='ADAPTER_SCAFFOLDED_NOT_CONNECTED', max_length=60)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_activation_decisions', to=settings.AUTH_USER_MODEL)),
                ('activation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='integrations.provideractivationrequest')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('DHA_HIE', 'DHA Health Information Exchange'), ('DHA_HWR', 'DHA Health Worker Registry'), ('PPB_PREMISES', 'PPB Premises Registry'), ('PPB_PRODUCT_REGISTER', 'PPB Product Register'), ('PPB_REGULATORY_ALERTS', 'PPB Regulatory Alerts'), ('PPB_RECALLS', 'PPB Product Recalls')], max_length=30)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox / Test'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activation_state', models.CharField(choices=[('REQUESTED', 'Activation requested'), ('UNDER_REVIEW', 'Under Platform Owner review'), ('SANDBOX_CONFIGURED', 'Sandbox configured'), ('SANDBOX_TESTING', 'Sandbox testing in progress'), ('SANDBOX_PASSED', 'Sandbox tests passed'), ('SECURITY_APPROVED', 'Security review approved'), ('PRODUCTION_APPROVED', 'Production approved by Platform Owner'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DECOMMISSIONED', 'Decommissioned'), ('REJECTED', 'Activation rejected')], default='REQUESTED', max_length=30)),
                ('truth_label', models.CharField(default='ADAPTER_SCAFFOLDED_NOT_CONNECTED', help_text='Empirical truth label for this integration. Must reflect actual operational state, not aspirational state.', max_length=60)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_provider_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider_type', 'environment'],
                'unique_together': {('provider_type', 'environment')},
            },
        ),
        migrations.AddField(
            model_name='provideractivationrequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='integrations.providerconfiguration'),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.providerconfiguration'),
        ),
        migrations.CreateModel(
            name='ProviderCredentialReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(help_text='e.g. CLIENT_ID, OAUTH_ENDPOINT, TLS_CERT_PATH, ISSUER_URL', max_length=40)),
                ('reference', models.CharField(help_text='Reference name only; the actual secret is stored in the secrets manager, not here.', max_length=500)),
                ('is_configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_credential_references', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_references', to='integrations.providerconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('allowed_hosts', models.JSONField(default=list, help_text='List of allowed hostnames for TLS validation. Empty = no connections permitted.')),
                ('is_active', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integrations.providerconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reachable', models.BooleanField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('truth_label', models.CharField(default='ADAPTER_SCAFFOLDED_NOT_CONNECTED', max_length=60)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='integrations.providerconfiguration')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['provider', 'state', '-created_at'], name='ix_intmsg_provider_state'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['state', 'next_retry_at'], name='ix_intmsg_retry'),
        ),
        migrations.AlterUniqueTogether(
            name='providercredentialreference',
            unique_together={('provider', 'credential_type')},
        ),
        migrations.AlterUniqueTogether(
            name='providerendpoint',
            unique_together={('provider', 'name')},
        ),
        migrations.AddIndex(
            model_name='providerhealthsnapshot',
            index=models.Index(fields=['provider', '-checked_at'], name='ix_provider_health_ts'),
        ),
    ]
