# Generated by Django 5.1.15 on 2026-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_claim_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconfiguration',
            name='activation_state',
            field=models.CharField(choices=[('REQUESTED', 'Activation requested'), ('UNDER_REVIEW', 'Under Platform Owner review'), ('SECURITY_REVIEW', 'Under security review'), ('SANDBOX_CONFIGURED', 'Sandbox configured'), ('SANDBOX_TESTING', 'Sandbox testing in progress'), ('SANDBOX_PASSED', 'Sandbox tests passed'), ('CERTIFICATION_REVIEW', 'Under certification review'), ('SECURITY_APPROVED', 'Security review approved'), ('PRODUCTION_APPROVED', 'Production approved by Platform Owner'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('DECOMMISSIONED', 'Decommissioned'), ('REJECTED', 'Activation rejected')], default='REQUESTED', max_length=30),
        ),
    ]
