# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccessevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccessevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_access_events', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='storedclinicaldocument',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_documents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='storedclinicaldocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_documents', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='storedclinicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccessevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='documents.storedclinicaldocument'),
        ),
        migrations.AddIndex(
            model_name='storedclinicaldocument',
            index=models.Index(fields=['tenant', 'patient', 'created_at'], name='ix_document_patient'),
        ),
        migrations.AddConstraint(
            model_name='storedclinicaldocument',
            constraint=models.UniqueConstraint(fields=('tenant', 'object_key'), name='uq_document_object_key_tenant'),
        ),
    ]
