# Generated by Django 5.1.15 on 2026-07-24 14:20

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeliveryAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_code', models.CharField(max_length=64)),
                ('recipient_name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_instructions', models.TextField(blank=True, default='')),
                ('route_zone', models.CharField(blank=True, default='', max_length=64)),
                ('cold_chain_capable', models.BooleanField(default=False)),
                ('controlled_medicine_capable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_number', models.CharField(db_index=True, max_length=64)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('GOVERNMENT', 'Government'), ('NGO', 'NGO'), ('INSURER', 'Insurer'), ('CORPORATE', 'Corporate'), ('INTERNAL', 'Internal')], max_length=64)),
                ('registration_number', models.CharField(blank=True, default='', max_length=128)),
                ('tax_number', models.CharField(blank=True, default='', max_length=128)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('billing_address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('billing_city', models.CharField(blank=True, default='', max_length=128)),
                ('billing_county', models.CharField(blank=True, default='', max_length=128)),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('billing_country', models.CharField(default='Kenya', max_length=100)),
                ('status', models.CharField(choices=[('PROSPECTIVE', 'Prospective'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='PROSPECTIVE', max_length=64)),
                ('risk_classification', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=64)),
                ('credit_status', models.CharField(choices=[('ACTIVE', 'Active'), ('CREDIT_HOLD', 'Credit Hold'), ('PAYMENT_REQUIRED', 'Payment Required'), ('MANUAL_REVIEW', 'Manual Review'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=64)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('payment_terms', models.CharField(default='NET30', max_length=128)),
                ('ordering_restrictions', models.TextField(blank=True, default='')),
                ('controlled_medicine_eligible', models.BooleanField(default=False)),
                ('cold_chain_capable', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerCommercialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_policy', models.CharField(blank=True, default='', max_length=128)),
                ('tax_treatment', models.CharField(default='STANDARD', max_length=64)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=128)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('controlled_product_authorized', models.BooleanField(default=False)),
                ('cold_chain_delivery_capable', models.BooleanField(default=False)),
                ('required_purchase_order_reference', models.BooleanField(default=False)),
                ('allowed_sku_categories', models.JSONField(blank=True, default=list)),
                ('blocked_skus', models.ManyToManyField(blank=True, related_name='+', to='medicines.commercialsku')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_profile', to='customers.customer')),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.location')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
    ]
