# Generated by Django 5.1.15 on 2026-07-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercommercialprofile',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.pricelist'),
        ),
        migrations.AddField(
            model_name='customercommercialprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='customerdeliveryaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_addresses', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerdeliveryaddress',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='customercommercialprofile',
            name='default_delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customerdeliveryaddress'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'status'], name='ix_customer_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer_number'), name='uq_customer_number'),
        ),
        migrations.AddConstraint(
            model_name='customerdeliveryaddress',
            constraint=models.UniqueConstraint(fields=('customer', 'address_code'), name='uq_customer_address_code'),
        ),
        migrations.AddConstraint(
            model_name='customercommercialprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer'), name='uq_customer_commercial_profile'),
        ),
    ]
