# Generated by Django 5.1.15 on 2026-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('GOVERNMENT', 'Government'), ('NGO', 'NGO'), ('INSURER', 'Insurer'), ('CORPORATE', 'Corporate'), ('INTERNAL', 'Internal')], max_length=64),
        ),
    ]
