# Generated by Django 5.1.15 on 2026-07-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRTerminologyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_url', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('is_global', models.BooleanField(default=False)),
                ('effective_period_start', models.DateTimeField(blank=True, null=True)),
                ('effective_period_end', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=160)),
                ('source_version', models.CharField(max_length=80)),
                ('licence', models.CharField(max_length=160)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminology_versions', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FHIRCodeSystemRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content_mode', models.CharField(default='COMPLETE', max_length=50)),
                ('concepts_json', models.JSONField(default=list)),
                ('is_global', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_systems', to='terminology.fhirterminologyversion')),
            ],
        ),
        migrations.CreateModel(
            name='FHIRValueSetRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('compose_json', models.JSONField(default=dict)),
                ('is_global', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_sets', to='terminology.fhirterminologyversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='fhirterminologyversion',
            index=models.Index(fields=['tenant', 'status'], name='ix_term_version_scope'),
        ),
        migrations.AddConstraint(
            model_name='fhirterminologyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'canonical_url', 'version'), name='uq_term_version_tenant'),
        ),
        migrations.AddConstraint(
            model_name='fhirterminologyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True), ('tenant__isnull', True)), fields=('canonical_url', 'version'), name='uq_term_version_global'),
        ),
        migrations.AddConstraint(
            model_name='fhirterminologyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', False), ('tenant__isnull', False)), models.Q(('is_global', True), ('tenant__isnull', True)), _connector='OR'), name='ck_term_explicit_scope'),
        ),
        migrations.AddConstraint(
            model_name='fhircodesystemregistration',
            constraint=models.UniqueConstraint(fields=('version', 'url'), name='uq_code_system_version'),
        ),
        migrations.AddConstraint(
            model_name='fhirvaluesetregistration',
            constraint=models.UniqueConstraint(fields=('version', 'url'), name='uq_value_set_version'),
        ),
    ]
