# Generated by Django 5.1.15 on 2026-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsubmissionattempt',
            name='business_status',
            field=models.CharField(default='UNKNOWN', max_length=64),
        ),
        migrations.AddField(
            model_name='claimsubmissionattempt',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claimsubmissionattempt',
            name='response_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='claimsubmissionattempt',
            name='response_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claimsubmissionattempt',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
    ]
