# Generated by Django 5.1.15 on 2026-07-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_claimsubmissionattempt_business_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreconciliationexception',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='insurance.prescriptionclaim'),
        ),
        migrations.AlterField(
            model_name='insuranceremittanceline',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='insurance.prescriptionclaim'),
        ),
    ]
