# Generated by Django 5.1.15 on 2026-07-28 03:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=80)),
                ('kra_pin', models.CharField(blank=True, max_length=40)),
                ('ppb_premises_licence_number', models.CharField(blank=True, max_length=80)),
                ('ppb_licence_expiry', models.DateField(blank=True, null=True)),
                ('superintendent_name', models.CharField(blank=True, max_length=200)),
                ('superintendent_ppb_number', models.CharField(blank=True, max_length=80)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=40)),
                ('onboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['ppb_licence_expiry'], name='ix_pharmacy_licence_exp')],
            },
        ),
        migrations.CreateModel(
            name='TenantLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-occurred_at'], name='ix_lifecycle_tenant')],
            },
        ),
    ]
