# Generated by Django 5.1.15 on 2026-07-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='licence_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='licence_source',
            field=models.CharField(choices=[('MANUAL', 'Entered by hand'), ('PPB_API', 'Confirmed with PPB')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='licence_verification_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
