# Generated by Django 5.1.15 on 2026-08-02 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_network', '0002_pharmacyprofile_licence_last_verified_at_and_more'),
        ('tenancy', '0002_alter_tenant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremisesVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for review'), ('UNDER_REVIEW', 'Under review'), ('CLARIFICATION_REQUIRED', 'Clarification required'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('verifier_declaration', models.TextField(blank=True)),
                ('truth_label', models.CharField(default='MANUAL_INTERNAL_VERIFICATION', max_length=60)),
                ('pharmacy_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='pharmacy_network.pharmacyprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premises_verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premises_verification_submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises_verification_requests', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremisesVerificationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_state', models.CharField(max_length=30)),
                ('declared_licence_number', models.CharField(blank=True, max_length=80)),
                ('declared_expiry', models.DateField(blank=True, null=True)),
                ('declared_superintendent', models.CharField(blank=True, max_length=200)),
                ('evidence_payload', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('truth_label', models.CharField(default='MANUAL_INTERNAL_VERIFICATION', max_length=60)),
                ('captured_at', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='premises_verification_snapshot_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises_verification_snapshots', to='tenancy.tenant')),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pharmacy_network.premisesverificationrequest')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='premisesverificationrequest',
            index=models.Index(fields=['tenant', 'state', '-created_at'], name='ix_pvr_tenant_state'),
        ),
        migrations.AddIndex(
            model_name='premisesverificationrequest',
            index=models.Index(fields=['pharmacy_profile', 'state'], name='ix_pvr_profile_state'),
        ),
        migrations.AddIndex(
            model_name='premisesverificationsnapshot',
            index=models.Index(fields=['tenant', '-captured_at'], name='ix_pvs_tenant_ts'),
        ),
        migrations.AddIndex(
            model_name='premisesverificationsnapshot',
            index=models.Index(fields=['verification_request', '-captured_at'], name='ix_pvs_request_ts'),
        ),
    ]
