# Generated by Django 5.1.15 on 2026-07-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryledgerentry_uq_inventory_ledger_idempotency_and_more'),
        ('sales', '0002_alter_pickingtask_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderallocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventorylocation'),
        ),
    ]
