# Generated by Django 5.1.15 on 2026-07-24 17:45

import apps.core.models
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_customer_type'),
        ('inventory', '0002_remove_inventoryledgerentry_uq_inventory_ledger_idempotency_and_more'),
        ('medicines', '0002_administrationroute_doseform_activesubstance_and_more'),
        ('organizations', '0001_initial'),
        ('sales', '0003_alter_salesorderallocation_location'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_quantity', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dispatchline',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='price_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='promotion_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='requested_batch_constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesreturnauthorization',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.quotation'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.UniqueConstraint(fields=('delivery_record', 'dispatch_line'), name='uq_delivery_dispatch_line'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_quantity__gt', 0)), name='chk_delivery_dispatched_positive'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_quantity__gte', 0)), name='chk_delivery_accepted_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_quantity__gte', 0)), name='chk_delivery_rejected_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('damaged_quantity__gte', 0)), name='chk_delivery_damaged_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('missing_quantity__gte', 0)), name='chk_delivery_missing_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('return_quantity__gte', 0)), name='chk_delivery_return_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_quantity__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('accepted_quantity'), '+', models.F('rejected_quantity')), '+', models.F('damaged_quantity')), '+', models.F('missing_quantity')))), name='chk_delivery_line_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='deliveryrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uq_delivery_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='dispatchpackage',
            constraint=models.UniqueConstraint(fields=('dispatch_order', 'package'), name='uq_dispatch_package'),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__gte', 0)), name='chk_picktask_picked_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('short_quantity__gte', 0)), name='chk_picktask_short_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pickingtask',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gte', django.db.models.expressions.CombinedExpression(models.F('picked_quantity'), '+', models.F('short_quantity')))), name='chk_picktask_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='chk_salesorder_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('tax_total__gte', 0)), name='chk_salesorder_tax_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_salesorder_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_quantity__gte', 0)), name='chk_soline_cancelled_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('backordered_quantity__gte', 0)), name='chk_soline_backorder_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('package_conversion__gt', 0)), name='chk_soline_package_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_subtotal__gte', 0)), name='chk_soline_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='chk_soline_tax_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='chk_soline_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('approved_quantity__lte', models.F('requested_quantity'))), name='chk_soline_approved_lte_requested'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_quantity__lte', models.F('requested_quantity'))), name='chk_soline_cancelled_lte_requested'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('approved_quantity'))), name='chk_soline_reserved_lte_approved'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__lte', models.F('reserved_quantity'))), name='chk_soline_allocated_lte_reserved'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__lte', models.F('allocated_quantity'))), name='chk_soline_picked_lte_allocated'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('packed_quantity__lte', models.F('picked_quantity'))), name='chk_soline_packed_lte_picked'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_quantity__lte', models.F('packed_quantity'))), name='chk_soline_dispatched_lte_packed'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('delivered_quantity__lte', models.F('dispatched_quantity'))), name='chk_soline_delivered_lte_dispatched'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__lte', models.F('delivered_quantity'))), name='chk_soline_returned_lte_delivered'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnauthorization',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uq_sales_return_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='chk_returnline_received_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salesreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='chk_returnline_received_lte_authorized'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicines.commercialsku'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_promotion_rule_code'),
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='chk_promotion_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='promotionrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gt', 0)), name='chk_promotion_min_qty_positive'),
        ),
    ]
