# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=80)),
                ('organization_type', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('OTHER', 'Other')], default='PHARMACY', max_length=40)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_organizations', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=80)),
                ('location_type', models.CharField(default='PHARMACY', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_locations', to='tenancy.tenant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organizations.organization')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='organizations.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'system', 'value'), name='uq_location_identifier_tenant')],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'status', 'name'], name='ix_org_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_org_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'organization', 'status'], name='ix_location_tenant_org'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_location_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='organizationidentifier',
            constraint=models.UniqueConstraint(fields=('tenant', 'system', 'value'), name='uq_org_identifier_tenant'),
        ),
    ]
