# Generated by Django 5.1.15 on 2026-08-03 06:28

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenancy', '0003_tenant_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('department_type', models.CharField(choices=[('DISPENSARY', 'Dispensary'), ('RETAIL', 'Retail Counter'), ('WHOLESALE', 'Wholesale'), ('STORES', 'Stores'), ('COLD_CHAIN', 'Cold Chain'), ('PROCUREMENT', 'Procurement'), ('FINANCE', 'Finance'), ('ADMINISTRATION', 'Administration'), ('QUALITY', 'Quality Assurance'), ('CLINICAL', 'Clinical Services')], default='DISPENSARY', max_length=40)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'site', 'status'], name='ix_department_tenant_site'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'site', 'code'), name='uq_department_tenant_site_code'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['tenant', 'user', 'is_active'], name='ix_dept_member_user'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'department', 'user'), name='uq_department_membership'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('tenant', 'user'), name='uq_department_primary_per_user'),
        ),
    ]
