# Generated by Django 5.1.15 on 2026-07-26 03:19

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.CharField(max_length=32)),
                ('pin_hash', models.CharField(max_length=255)),
                ('pin_set_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_pin', models.BooleanField(default=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_credentials', to='tenancy.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_credential', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PosSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(max_length=120)),
                ('register_id', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=40)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='identity.poscredential')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='poscredential',
            index=models.Index(fields=['tenant', 'login_id'], name='identity_po_tenant__666a07_idx'),
        ),
        migrations.AddConstraint(
            model_name='poscredential',
            constraint=models.UniqueConstraint(fields=('tenant', 'login_id'), name='uq_pos_credential_tenant_login'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['tenant', 'device_id'], name='identity_po_tenant__1632a8_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['token_hash'], name='identity_po_token_h_78072a_idx'),
        ),
    ]
