# Generated by Django 5.1.15 on 2026-07-22 13:15

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_outbox', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='tenancy.tenant')),
                ('outbox_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prescription.integrationoutbox')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_number', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VERIFIED', 'Verified'), ('DISPENSED_PARTIALLY', 'Dispensed partially'), ('DISPENSED', 'Dispensed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('CLINICAL_REVIEW', 'Clinical review'), ('BLOCKED', 'Blocked'), ('APPROVED', 'Approved'), ('DISPENSING', 'Dispensing'), ('READY_FOR_PAYMENT', 'Ready for payment'), ('PAID', 'Paid'), ('DISPENSED', 'Dispensed'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=50)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('substitution_policy', models.CharField(default='ALLOWED', max_length=50)),
                ('clinical_context_hash', models.CharField(blank=True, max_length=64)),
                ('clinical_review_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_clinically_approved', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='practitioners.practitioner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionDispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='organizations.location')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage_instruction', models.TextField()),
                ('dose_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=50)),
                ('frequency_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('refills_authorized', models.PositiveIntegerField(default=0)),
                ('is_controlled', models.BooleanField(default=False)),
                ('route', models.CharField(blank=True, max_length=80)),
                ('canonical_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionFill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_dispensed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='prescription.prescriptiondispense')),
                ('substituted_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='prescription.prescriptionitem')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('workflow_state', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescriptionfill')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription.prescriptionitem')),
                ('substitute_medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by_provider', models.CharField(max_length=100)),
                ('verification_payload', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrescriptionWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('context_hash', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='prescription.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=50)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(max_length=50)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('certificate_id', models.CharField(blank=True, max_length=255)),
                ('rate_limit', models.PositiveIntegerField(default=100)),
                ('retry_policy', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configurations', to='tenancy.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='integrationoutbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'correlation_id'), name='uq_integration_correlation_tenant'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_integration_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('tenant', 'prescription_number'), name='uq_prescription_number_tenant'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiondispense',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_dispense_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='providerconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider_code'), name='uq_provider_config_tenant'),
        ),
    ]
