# Generated by Django 5.1.15 on 2026-07-22 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('prescription', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'status'], name='ix_prescription_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'workflow_state'], name='ix_prescription_workflow'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'patient'], name='ix_prescription_patient'),
        ),
    ]
