# Generated by Django 5.1.15 on 2026-07-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('prescription', '0003_clinicalsubstitution_clinicalworkitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglabel',
            name='stored_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedclinicaldocument'),
        ),
    ]
