# Generated by Django 5.1.15 on 2026-07-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_dispensinglabel_stored_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalworkitem',
            name='queue_type',
            field=models.CharField(choices=[('PRESCRIPTION_INTAKE', 'Prescription intake'), ('LEGAL_VALIDATION', 'Legal validation'), ('CLINICAL_REVIEW', 'Clinical review'), ('CRITICAL_DUR_FINDING', 'Critical DUR finding'), ('PRESCRIBER_CLARIFICATION', 'Prescriber clarification'), ('PATIENT_CLARIFICATION', 'Patient clarification'), ('PHARMACIST_VERIFICATION', 'Pharmacist verification'), ('READY_FOR_DISPENSING', 'Ready for dispensing'), ('DISPENSING_PREPARATION', 'Dispensing preparation'), ('FINAL_CHECK', 'Final check'), ('READY_FOR_COUNSELLING', 'Ready for counselling'), ('READY_FOR_SUPPLY', 'Ready for supply'), ('PARTIAL_DISPENSING_FOLLOW_UP', 'Partial dispensing follow-up'), ('REPEAT_DUE', 'Repeat due'), ('EARLY_REPEAT_REVIEW', 'Early repeat review'), ('CONTROLLED_MEDICINE_REVIEW', 'Controlled-medicine review'), ('PATIENT_RETURN_INSPECTION', 'Patient return inspection'), ('REVERSAL_APPROVAL', 'Reversal approval')], max_length=80),
        ),
        migrations.AlterField(
            model_name='dispensingreversal',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='prescription.medicinesupply'),
        ),
        migrations.AlterField(
            model_name='medicinesupply',
            name='status',
            field=models.CharField(choices=[('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('PARTIALLY_REVERSED', 'Partially reversed'), ('REVERSED', 'Reversed')], max_length=20),
        ),
    ]
