# Generated by Django 5.1.15 on 2026-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('prescription', '0005_alter_clinicalworkitem_queue_type_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicalworkitem',
            name='uq_active_clinical_work_item',
        ),
        migrations.AddConstraint(
            model_name='clinicalworkitem',
            constraint=models.UniqueConstraint(condition=models.Q(('dispensing_episode__isnull', True), ('status__in', ['OPEN', 'IN_PROGRESS'])), fields=('tenant', 'queue_type', 'prescription'), name='uq_active_rx_work_item'),
        ),
        migrations.AddConstraint(
            model_name='clinicalworkitem',
            constraint=models.UniqueConstraint(condition=models.Q(('dispensing_episode__isnull', False), ('status__in', ['OPEN', 'IN_PROGRESS'])), fields=('tenant', 'queue_type', 'prescription', 'dispensing_episode'), name='uq_active_episode_work_item'),
        ),
    ]
