# Generated by Django 5.1.15 on 2026-07-25 07:56

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('prescription', '0006_remove_clinicalworkitem_uq_active_clinical_work_item_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingepisode',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='collection_proof_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='collector_id_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='collector_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='collector_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='collector_relationship',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='controlled_authority_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='controlled_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='dispensingepisode',
            name='tender_type',
            field=models.CharField(default='CASH', max_length=64),
        ),
        migrations.CreateModel(
            name='PosLabelReprintAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reprint_reason', models.CharField(max_length=255)),
                ('reprinted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprints', to='prescription.dispensinglabel')),
                ('reprinted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PosDeviceHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('device_type', models.CharField(default='TERMINAL', max_length=64)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('OFFLINE', 'Offline')], default='OK', max_length=32)),
                ('printer_paper_level', models.CharField(default='OK', max_length=32)),
                ('scanner_connected', models.BooleanField(default=True)),
                ('cash_drawer_open', models.BooleanField(default=False)),
                ('network_latency_ms', models.IntegerField(default=0)),
                ('battery_level_pct', models.IntegerField(blank=True, null=True)),
                ('storage_used_pct', models.IntegerField(default=0)),
                ('telemetry_data', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'device_id'), name='uq_pos_device_health_id')],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PosShiftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_number', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('RECONCILED', 'Reconciled')], default='OPEN', max_length=32)),
                ('controlled_stock_start_count', models.IntegerField(default=0)),
                ('controlled_stock_end_count', models.IntegerField(default=0)),
                ('discrepancy_declared', models.BooleanField(default=False)),
                ('declaration_notes', models.TextField(blank=True, default='')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'shift_number'), name='uq_pos_shift_number')],
            },
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
    ]
