# Generated by Django 5.1.15 on 2026-07-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_pos_enterprise_dispensing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingepisode',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('CHECKING', 'Checking'), ('READY_FOR_PAYMENT', 'Ready for payment'), ('PAID', 'Paid'), ('READY_FOR_COLLECTION', 'Ready for collection'), ('READY_FOR_SUPPLY', 'Ready for supply'), ('PARTIALLY_SUPPLIED', 'Partially supplied'), ('SUPPLIED', 'Supplied'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed'), ('RETURNED', 'Returned')], default='DRAFT', max_length=30),
        ),
    ]
