# Generated by Django 5.1.15 on 2026-07-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_update_dispensing_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingepisode',
            name='payment_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='posshiftrecord',
            name='outstanding_episode_count',
            field=models.IntegerField(default=0),
        ),
    ]
