# Generated by Django 5.1.15 on 2026-07-25 14:53

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('prescription', '0010_canonical_payment_state'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('FAKE', 'Fake provider (test/demo)'), ('MPESA', 'M-PESA')], max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('request_reference', models.CharField(max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('ACCEPTED', 'Accepted by provider'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed out'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=20)),
                ('request_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('register_id', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_settled', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('amount_reversed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('OPEN', 'Open'), ('PARTIALLY_SETTLED', 'Partially settled'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('REVERSAL_PENDING', 'Reversal pending'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=30)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('version', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dispensing_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='prescription.dispensingepisode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('FAKE', 'Fake provider (test/demo)'), ('MPESA', 'M-PESA')], max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('event_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('request_reference', models.CharField(blank=True, default='', max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('authenticated', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('AUTHENTICATED', 'Authenticated'), ('PROCESSED', 'Processed'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected'), ('UNMATCHED', 'Unmatched')], default='RECEIVED', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('settlement_reference', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('CASH', 'Cash at till'), ('CARD_MANUAL', 'Manually confirmed card approval'), ('PROVIDER_EVENT', 'Provider callback'), ('PROVIDER_QUERY', 'Provider status query')], max_length=20)),
                ('settled_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='prescription.paymentattempt')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='prescription.paymentsettlement')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentTender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MPESA', 'M-PESA')], max_length=20)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('FAKE', 'Fake provider (test/demo)'), ('MPESA', 'M-PESA')], default='MANUAL', max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('reversed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('register_id', models.CharField(blank=True, default='', max_length=128)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('PENDING', 'Pending'), ('PARTIALLY_SETTLED', 'Partially settled'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSAL_PENDING', 'Reversal pending'), ('REVERSED', 'Reversed')], default='ALLOCATED', max_length=30)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='prescription.paymentintent')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_tenders', to='prescription.posshiftrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            bases=(apps.core.models.TenantConsistencyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='payment_tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='prescription.paymenttender'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='prescription.paymenttender'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['tenant', 'status'], name='ix_payment_intent_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_payment_intent_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CREATED', 'OPEN', 'PARTIALLY_SETTLED', 'REVERSAL_PENDING'])), fields=('dispensing_episode',), name='uq_payment_intent_one_active_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='chk_payment_intent_due_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_settled__gte', 0)), name='chk_payment_intent_settled_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_reversed__gte', 0)), name='chk_payment_intent_reversed_nonneg'),
        ),
        migrations.AddIndex(
            model_name='paymentproviderevent',
            index=models.Index(fields=['tenant', 'provider', 'request_reference'], name='ix_provider_event_reqref'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('tenant', 'provider', 'event_id'), name='uq_payment_provider_event_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentreversal',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_payment_reversal_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentreversal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payment_reversal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttender',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_payment_tender_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymenttender',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('tenant', 'provider', 'external_reference'), name='uq_payment_tender_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='paymenttender',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='chk_payment_tender_allocated_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymenttender',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__gte', 0)), name='chk_payment_tender_settled_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='paymenttender',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_amount__gte', 0)), name='chk_payment_tender_reversed_nonneg'),
        ),
        migrations.AddIndex(
            model_name='paymentsettlement',
            index=models.Index(fields=['tenant', 'provider_reference'], name='ix_settlement_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_payment_settlement_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payment_settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_payment_attempt_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_reference'), name='uq_payment_attempt_request_reference'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='chk_payment_attempt_amount_positive'),
        ),
    ]
