# Generated by Django 5.1.15 on 2026-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0011_paymentattempt_paymentintent_paymentproviderevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poslabelreprintaudit',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='poslabelreprintaudit',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poslabelreprintaudit',
            name='printer',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='poslabelreprintaudit',
            name='status',
            field=models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='SUCCEEDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='poslabelreprintaudit',
            name='reprint_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
