# Generated by Django 5.1.15 on 2026-07-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_shift', '0001_initial'),
        ('prescription', '0012_label_reprint_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttender',
            name='operator_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_tenders', to='pos_shift.operatorshift'),
        ),
        migrations.AddField(
            model_name='paymenttender',
            name='register_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_tenders', to='pos_shift.registersession'),
        ),
    ]
