# Generated by Django 5.1.15 on 2026-07-28

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0014_dispensingepisode_payment_register_context'),
        ('pos_shift', '0002_shiftreport_shiftreportreprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPrintDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('RETAIL_RECEIPT', 'Retail receipt'), ('PRESCRIPTION_RECEIPT', 'Prescription receipt'), ('MEDICINE_LABEL', 'Medicine label'), ('CASH_MOVEMENT_RECEIPT', 'Cash movement receipt'), ('X_REPORT', 'X report'), ('Z_REPORT', 'Z report'), ('REVERSAL_RECEIPT', 'Reversal receipt'), ('INSURANCE_SUPPORTING_DOCUMENT', 'Insurance supporting document')], max_length=48)),
                ('document_number', models.CharField(max_length=128)),
                ('snapshot', models.JSONField(default=dict)),
                ('document_hash', models.CharField(max_length=64)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_documents', to='prescription.dispensingepisode')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_documents', to='prescription.dispensinglabel')),
                ('register_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_documents', to='pos_shift.registersession')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_documents', to='prescription.paymentsettlement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'document_type'], name='ix_pos_print_doc_tenant_type')],
            },
        ),
        migrations.CreateModel(
            name='PosPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printer', models.CharField(blank=True, default='', max_length=128)),
                ('transport', models.CharField(choices=[('WINDOWS_SPOOLER', 'Windows spooler'), ('ESCPOS_USB', 'ESC/POS USB'), ('ESCPOS_NETWORK', 'ESC/POS network'), ('ANDROID_BLUETOOTH', 'Android Bluetooth'), ('ANDROID_NETWORK', 'Android network'), ('SIMULATOR', 'Deterministic simulator'), ('PDF_FALLBACK', 'PDF fallback')], default='SIMULATOR', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RENDERED', 'Rendered'), ('SENDING', 'Sending'), ('PRINTED', 'Printed'), ('FAILED', 'Failed'), ('RETRY_REQUIRED', 'Retry required'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=32)),
                ('copy_classification', models.CharField(choices=[('ORIGINAL', 'Original'), ('REPRINT', 'Reprint')], default='ORIGINAL', max_length=16)),
                ('copy_number', models.PositiveIntegerField(default=1)),
                ('reprint_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='prescription.posprintdocument')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.location')),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='ix_pos_print_job_tenant_status'), models.Index(fields=['tenant', 'printer'], name='ix_pos_prn_job_printer'), models.Index(fields=['tenant', 'branch', 'status'], name='ix_pos_print_job_branch'), models.Index(fields=['tenant', 'device_id', 'status'], name='ix_pos_prn_job_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='posprintdocument',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_number'), name='uq_pos_print_document_number'),
        ),
        migrations.AddConstraint(
            model_name='posprintdocument',
            constraint=models.UniqueConstraint(condition=Q(('settlement__isnull', False)), fields=('settlement', 'document_type'), name='uq_pos_print_document_settlement_type'),
        ),
        migrations.AddConstraint(
            model_name='posprintdocument',
            constraint=models.UniqueConstraint(condition=Q(('label__isnull', False)), fields=('label', 'document_type'), name='uq_pos_print_document_label_type'),
        ),
        migrations.AddConstraint(
            model_name='posprintjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_pos_print_job_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='posprintjob',
            constraint=models.UniqueConstraint(fields=('document', 'copy_number'), name='uq_pos_print_job_document_copy'),
        ),
    ]
